### ISSUE TITLE
The idea of optional parameter tagname is not clear. Is this related to table name ?

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#10]
Tagname option is not clear. Is this similar to database collection name?

**Comment by DanielHindi** [comment]
So the Tag is meant to give you an additional filtration method on the type of document you are saving/retrieving

Think of your index (not unique) as appId, pluginId, InstanceId and *tag* 

while tag may be null and function normally you may use it to separate out document types such as

([appId], [pluginId], [InstanceId] ,"Content")
,([appId], [pluginId], [InstanceId] ,"Design")
and ([appId], [pluginId], [InstanceId] ,"Settings")

or

([appId], [pluginId], [InstanceId] ,"MasterRecord")
and ([appId], [pluginId], [InstanceId] ,"DetailRecords")

or

([appId], [pluginId], [InstanceId] ,"Company")
and ([appId], [pluginId], [InstanceId] ,"Employees")

ref: https://github.com/BuildFire/sdk/wiki/How-to-use-Datastore#buildfiredatastoreget-tag-optional-callback

**Comment by deepakshrma** [comment]
Thanks Daniel.
