### ISSUE TITLE
Issue with BuildFire-Audio-Player-Service.

### ISSUE THREAD

**Issue by vineetasharma** [BuildFire/sdk#101]
buildfire.services.media.audioPlayer.setTime(sec) method not working properly to forward/backward the current track.

**Comment by DanielHindi** [comment]
Seems to be working fine in the Audio Player example
https://github.com/BuildFire/sdk/blob/master/plugins/audioPlayerExample/widget/index.html#L148

Can you give me more information or a snippet?

**Comment by vineetasharma** [comment]
Now its working fine.
