### ISSUE TITLE
Errors in http://int2.myapp.buildfire.com/ console

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/sdk#105]
![screenshot from 2015-09-16 12 42 45](https://cloud.githubusercontent.com/assets/3328800/9898866/82d5c67a-5c73-11e5-91e6-271d7d9d55cb.png)

**Comment by DanielHindi** [comment]
is this still an issue?

**Comment by sakshityagi** [comment]
Yes. Just tried again. Still there.

**Comment by DanielHindi** [comment]
We fixed the logger reference to accommodate for lack of it in the context. However, This is still exposing 2 other issues in your plugin. 
1) its sending undefined in your tags (sometimes)
2) A save is occurring on load. This usually happens because of an angular $watch triggering on load

**Comment by sakshityagi** [comment]
This is fixed now.
