### ISSUE TITLE
How user can get sorted data using datastore plugin?

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#11]
In datastore plugin, User can fetch, update data. Is there any possible way to get sorted data?

**Comment by DanielHindi** [comment]
The onUpdate event will give you the data as is. however if you'd like to use that event to trigger a sorted search you may

https://github.com/BuildFire/sdk/wiki/How-to-use-Datastore#buildfiredatastoresearchoptions-tag-optional-callback

**Comment by deepakshrma** [comment]
Search api is not working.. 
https://github.com/BuildFire/sdk/issues/13

**Comment by dahabi** [comment]
we pushed some fixes ,pull and try it again please

**Comment by deepakshrma** [comment]
//insert
buildfire.datastore.insert({"firstName":"Laura","lastName":"Bascoe"},'names2', function(){
    $scope.status='imported ' + data.length + ' names.';
    $scope.$apply();
});

//search
function search() {
    var pattern = '/*';
    buildfire.datastore.search({
        filter:{"$json.firstName":{"$regex":pattern}}
        sort:{"field":"rank","desc":true},
       ,page:0
        ,pageSize:pageSize + 1 // the plus one is to check if there are any more
    },'names2',function(err,results) {
        console.log("Data:",results)
    });

}
search();
