### ISSUE TITLE
buildfire.datastore.insert doesn't have duplicate check.

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#12]
There is no check for duplicate data entry in buildfire.datastore.insert...

```js 
buildfire.datastore.insert({name:'user1',age:24,lname:'lastname1'},'user',function(err,data){
            console.log('#####insert####\n',err, data.id);
            //55ae097102f5cfa80ff8bfce
        });    

buildfire.datastore.insert({name:'user1',age:24,lname:'lastname1'},'user',function(err,data){
            console.log('#####insert####\n',err, data.id);
            //55ae0a2a02f5cfa80ff8bfd5
        });
```
Not sure whether about api. If it insert multiple data. Then i get single object when i search for same user name.
```js 
buildfire.datastore.get({name:'user1'},function(err,data) {
            console.log('#####get####\n',err, data);
            //55ae0a2a02f5cfa80ff8bfd5
        });
```
This only returns single data object.

**Comment by DanielHindi** [comment]
You use the [save] method for an upsert functionality ref https://github.com/BuildFire/sdk/wiki/How-to-use-Datastore#buildfiredatastoresave-obj-tag-optional-callback

However, This may be a good option to add. We will look into this

**Comment by deepakshrma** [comment]
Hi Daniel Thanks for quick reply. Kindly create a ticket for addition functionality :-D so that i can close this ticket.
