### ISSUE TITLE
Is there any api available for bulk import/export in buildfire.datastore ?

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#16]
For my people plugin, I need a feature where user can upload peoples data in bulk. So that he/she dont have to upload data indivisually. Is there any api available to upload/get in a specific tag in bulk.

**Comment by DanielHindi** [comment]
Not currently but will consider implementing it.

**Comment by deepakshrma** [comment]
Thanks for reply. Closing the issue

**Comment by DanielHindi** [comment]
We are creating an bulk insert api. I will keep this ticket open and reports the new wiki link for you once its complete

**Comment by DanielHindi** [comment]
Here it is
https://github.com/BuildFire/sdk/wiki/How-to-use-Datastore#buildfiredatastorebulkinsert-obj-tag-optional---callback

there is also example code in the SDK /plugins/exampleSImpleSearch
https://github.com/BuildFire/sdk/blob/master/plugins/exampleSimpleSearch/control/content/index.html
