### ISSUE TITLE
Wiki Page "How to Fill in plugin.json" not loading correctly

### ISSUE THREAD

**Issue by kickinbahk** [BuildFire/sdk#166]
Not sure if it is some un-blocked code or if it is due to the name. When you try to go to https://github.com/BuildFire/sdk/wiki/How-to-fill-in-plugin.json it will flash the content for a second, then show this error page: 

![screen shot 2015-12-10 at 12 42 07 pm](https://cloud.githubusercontent.com/assets/10123801/11727918/aaef4f2c-9f3b-11e5-9995-4f9958f71a8e.png)

**Comment by ianblair44** [comment]
Works fine for me. Try a different browser.

**Comment by NancyHaddad** [comment]
Works for me too actually

**Comment by kickinbahk** [comment]
Seems Pretty JSON chrome extension was the culprit. 

It is a pretty common for developers to have this or some similar extension. Can we change the name of the title in the wiki to **How to Fill in "plugin.json" File**

Based of my testing, it is specifically the title causing the issue and the quotes keep the extension from thinking the page is json.

**Comment by NancyHaddad** [comment]
I changed it

**Comment by kickinbahk** [comment]
@NancyHaddad Thanks!
