### ISSUE TITLE
Issue in iframe sandbox with angular ui-router: thows Failed to read the 'cookie' property from 'Document'

### ISSUE THREAD

**Issue by sandeepchhapola** [BuildFire/sdk#19]
When i include angular ui-router in my application. SDK throws error
======================================================
Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
======================================================
![code that generate error](https://cloud.githubusercontent.com/assets/7790671/8852724/7c205090-3174-11e5-828a-01954ba0d9dd.png)
![error](https://cloud.githubusercontent.com/assets/7790671/8852723/7c1e57fe-3174-11e5-9ed0-35bc0b1fe384.png)

**Comment by DanielHindi** [comment]
We will look into this. But is there any reason why you're not using ngRoute ?

**Comment by deepakshrma** [comment]
Daniel, ngRoute is almost deprecated. Most of the angular app use ui-router. It is easy to use and easy to manage code. It comes with lost of feature like resolve. It has multiple view concept

**Comment by DanielHindi** [comment]
I'm not against ui-route. However sandbox restricts cookies. This will cause a complications

**Comment by DanielHindi** [comment]
Get/pull latest SDK and try again please

**Comment by deepakshrma** [comment]
Same issue with widget also, iframe  sandbox="allow-scripts allow-forms allow-same-origin". Change it too.
