### ISSUE TITLE
Is there any projection available in datastrore API's ?

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#21]
In most of the Database there is a feature of projecting data. It helps to minimize the throughput time

**Comment by DanielHindi** [comment]
Can you explain a little more

**Comment by deepakshrma** [comment]
I want something like this: http://docs.mongodb.org/manual/reference/operator/aggregation/project/
To reduce the size of json data as per requirement

**Comment by DanielHindi** [comment]
Ahh good observation. Before I suggest a solution is your main concern
saving or retrieving?

**Comment by deepakshrma** [comment]
In most of the Database they provide in fetch, So it would be better if we can provide this option in search, get and update. We can also check other library like mongoose, mongodb to see organization standards.

**Comment by DanielHindi** [comment]
I will look into this. However, remember this isn't a standard database
it's is very complex and needs to be secure so certain features were
purposely not created. Not to say this is one of them but I'll get back to
you

**Comment by deepakshrma** [comment]
Thanks Daniel for quick reply

**Comment by dahabi** [comment]
the search API updated ,its now take a new option "fields" in order to limit the  result, check the wiki
https://github.com/BuildFire/sdk/wiki/How-to-use-Datastore#buildfiredatastoresearchoptions-tag-optional-callback

**Comment by NancyHaddad** [comment]
Can we close this ticket?
