### ISSUE TITLE
My plugin inherit css style from the default theme

### ISSUE THREAD

**Issue by bfsiumm** [BuildFire/sdk#237]
Hi all,

I'm developing a plugin that connects to a remote server. I'm using a third party UI framework within the project. 
I want my plugin to preserve it's own style and not to inherit from the default theme. For that i added the following meta tag         "    meta name="buildfire" content="disableTheme"      "
But i think it doesn't work. 

Hier is a preview to illustrate the case:

that's what 'm getting when i test my plugin on localhost
<img width="308" alt="buildfire emulator result" src="https://cloud.githubusercontent.com/assets/20697949/17205334/d3bdc634-54aa-11e6-9767-b7b2e38c3941.png">

and hier is the result when i install my plugin in an app and running it on a real device
![real device result-1](https://cloud.githubusercontent.com/assets/20697949/17205377/1452145c-54ab-11e6-92bb-849f8ec752ed.png)

Result when i add the  "   meta name="buildfire" content="disableTheme"       "
( same result on localhost and on a real device)
<img width="317" alt="capture d ecran 2016-07-26 a 12 48 06 1" src="https://cloud.githubusercontent.com/assets/20697949/17205394/3427fac6-54ab-11e6-995a-b3d4bd9a6897.png">

Any help would be appreciated
Thanks

**Comment by DanielHindi** [comment]
Hello, we have received this issue and will look into it shortly.

**Comment by abuturla** [comment]
@bfsiumm  Please send a copy of your plugin to devsupport@buildfire.com so that I can take a look.

**Comment by bfsiumm** [comment]
already sent

**Comment by abuturla** [comment]
@bfsiumm I see that you have uploaded your plugin to the developer portal, but what we'll need to assist you is a zipped copy of your plugin via email. Alternatively if the code for the plugin is in GitHub, you can grant me access to the repo. Thanks.

**Comment by bfsiumm** [comment]
Hi,

I’ve already sent the zip folders ti the developer@buildfire.com<mailto:developer@buildfire.com>.
Hier again you will find the zip for the project.

Please note that actually i’m working only on the widget side.

**Comment by abuturla** [comment]
@bfsiumm  I have received the files and will be taking a look into it. Thanks.

**Comment by abuturla** [comment]
@bfsiumm I believe we have identified the code that was causing the issue. Please update to the latest version of the BuildFire SDK and try again.

**Comment by bfsiumm** [comment]
Hi,

I’m now using the latest version of your SDK.

The issue is resolved only when i test my plugin on the localhost( the plugin UI is correctly  displayed and the theme style is not applied in my plugin).

When i install my plugin and preview it online on buildfire.com<http://buildfire.com>, the plugin UI is correctly displayed  but theme style still applied to my plugin)

When i run the plugin on a real device, the result is completely unexpected.

Please see the file attached for what i obtained in the 3 cases.


[cid:4B128E7D-A857-4900-A9FE-39936F07EC89@router5b5d30.com][cid:F5DE3510-7B17-4A0B-9BD2-7B460AF63B6D@router5b5d30.com][cid:D260BC57-BFEE-4933-99DF-42F8B85C1CD3@router5b5d30.com]
Best regards

Le 1 août 2016 à 20:48, abuturla <notifications@github.com<mailto:notifications@github.com>> a écrit :


@bfsiumm<https://github.com/bfsiumm> I believe we have identified the code that was causing the issue. Please update to the latest version of the BuildFire SDK and try again.

**Comment by abuturla** [comment]
@bfsiumm Can you clarify what you mean by the UI is correctly displayed, but the theme style is still applied?

Also, your file attachments didn't make it to GitHub. The following [link](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) explains how to add images to a GitHub issue. Thanks.

**Comment by bfsiumm** [comment]
result when testing on localhost
<img width="344" alt="test result on localhost" src="https://cloud.githubusercontent.com/assets/20697949/17375054/b37f9280-59af-11e6-8132-6aa86cc0011c.png">

result when testing on buildfire.com

<img width="342" alt="test result on buildfire com emulator" src="https://cloud.githubusercontent.com/assets/20697949/17375082/da736146-59af-11e6-9239-384ca21b3888.png">

result on a real device 
![test result on a real deivce](https://cloud.githubusercontent.com/assets/20697949/17375095/e84f4faa-59af-11e6-84d2-d19d931b30b2.png)

I hope it's clear now

Thanks

**Comment by abuturla** [comment]
@bfsiumm  Thanks, the screen shots helped clarify. We mad some additional changes that should help rectify the issues with the Control Panel (buildfire.com) and with the app on the device.

**Comment by bfsiumm** [comment]
Hi Aburtula,
Thanks for your Help.
All issues relating the theme are resolved.
However, it still one thing i can't understand. why is the tab bar still hanging on the top when running the plugin on a device, while it's correctly placed( on the bottom ) when testing the app online on the  buildfire emulator.

![screenshot_20160804-103044](https://cloud.githubusercontent.com/assets/20697949/17395607/a281f7ae-5a2f-11e6-95fa-d00be6969cc6.png)

**Comment by abuturla** [comment]
@bfsiumm I'm glad that we were able to help.  

I noticed that for iPhone the navigation bar appears at the bottom, while for Android it appears at the top. My understanding is that Ionic positions navigation differently by platform.  I'd suggest referring to the Ionic [documentation](http://ionicframework.com/docs/api/provider/%24ionicConfigProvider/) on this.

![img_0519](https://cloud.githubusercontent.com/assets/19535979/17410361/309c5a82-5a28-11e6-90c8-da7f128f330f.PNG)
