### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by Vladimir2376** [BuildFire/sdk#238]
![Uploading 1234.png…]()
Hi! I need translate on Russian language for the login page. How to do it?

**Comment by Vladimir2376** [comment]
Hi! My application users are Russian-speaking people. I need translate on Russian language for the login page and the page with push notification. 
Please tell me the names of the files that need to be translated. 
Or translate on Russian language, I'll pay.

**Comment by DanielHindi** [comment]
Hello Vladimir,

All the string swaps are located in Control Panel > Settings > App Settings 
Where you can change hard coded string to whatever you want

However, Inside Login and Push notification the few strings there are still not configurable. While this is on our road map I dont think we will get to it until another month or two.
