### ISSUE TITLE
need to build bitcoin mobile wallet. 

### ISSUE THREAD

**Issue by doniachen** [BuildFire/sdk#239]
Hello,
I want to build bitcoin mobile wallet using build fire. please help and guide me.

**Comment by DanielHindi** [comment]
Hello doniachen,

I love the idea! Dealing with bitcoin can be a bit tricky. However, it is doable. You need to find the right bitcoin provider/service that you want to integrate with. So there is some planning involved before you start coding away.

If you need a development team to help you with this I would suggest emailing support@buildfire.com with this where they can help you find certified BuildFire developers who can help you build this.

Best of luck. I'd be one of your first 💯  customers
