### ISSUE TITLE
BuildFire App Help

### ISSUE THREAD

**Issue by robbgreen** [BuildFire/sdk#240]
Hi,

Thanks for your help in advance.

We would like to set up a Barber App like 'Cue', users when coming to the app would be asked if they are barbers or clients, from there they would be taken to different pages within the app deepening on their role. 

Would it be possible to:

1. Have different user roles upon entering the app for the first time? If not then is there another way we could do this?

2. Have a booking form on each barber's page we set up?

3. Would it be possible to have an e-commerce part before the booking form so you can pay for the hair cut?

4. Do you offer a review system so clients could review the barbers?

5. An alternative to the booking form would be a option to cue in a kind of live form, would this be possible, so clients can see where they are in the cue and barbers know who is next?

Many thanks!

Rob

**Comment by DanielHindi** [comment]
Hello robbgreen,

Great use of BuildFire... We in fact have many apps that do this. Here are your options:

> 1. Have different user roles upon entering the app for the first time? If not then is there another way we could do this?

If this is a **non secure** fork you can simply create a Folder Plugin in the launcher asking the user if they are a Customer or a Barber and then take them into sub-menus

if it is a **secure fork** meaning they would have to log in to be allowed into the Barber side you can do this several ways here are a couple of options

1. Fork the existing Folder Plug  ( its open source in [github](https://github.com/BuildFire/?utf8=%E2%9C%93&query=folder)  ) And add in a White List of approved barber users into that section
2. You can certainly develop your own plugin from scratch.
3. You can look into using User tagging as a filtration mechanism

**note: I'd study the next answers to see if you even need the barber side (see below)**

> 2 . Have a booking form on each barber's page we set up?

 Once the customer enters into the "Customer" Section of the app you can add a Global booking plugin or a separate booking plugin for each barber
![image](https://cloud.githubusercontent.com/assets/492189/17410065/f7a4ef60-5a26-11e6-89de-2556bae7eee1.png)

Is a really good option you can also use **Calendly** plugin 

This way each Barber has his own Calendar and can manage it on their own from YouCanBook.me * which means you dont need the Barber Section on the app

> 3 .Would it be possible to have an e-commerce part before the booking form so you can pay for the hair cut?

Yes, YouCanBook.me plugin accepts payments

> 4 . Do you offer a review system so clients could review the barbers?

We are about to release customer review plugin very soon. you can have one for each Barber or have on Global review

> 5 . An alternative to the booking form would be a option to cue in a kind of live form, would this be possible, so clients can see where they are in the cue and barbers know who is next?

YouCanBook.me plugin show which slots are empty and which are not. You could also develop a live queue and wait list plugin if needed

I hope this helps

**Comment by robbgreen** [comment]
Hi Daniel, 

Thanks for the quick reply, that's great help, will definitely follow your advise, cheers buddy!  : D

**Comment by DanielHindi** [comment]
Happy to help we are here if you need us 👍

**Comment by robbgreen** [comment]
Hi Daniel,

Thanks again for you help, I have just a few additional questions:

> 1 -  “if it is a secure fork meaning they would have to log in to be allowed into the Barber side you can do this several ways here are a couple of options
> 	1	Fork the existing Folder Plug ( its open source in github ) And add in a White List of approved barber users into that section”

A. Would it be possible to allow any barber to join and just blacklist them if needed rather than white list? 

B. Now we can have a different “door” for barbers could I add the functionality so that they can add their own listing/profile, for example add image, contact and ‘Youcanbookme’ / ‘Calendy’ details?

> 2 - Would it be possible to have an e-commerce part before the booking form so you can pay for the hair cut?
> Yes, YouCanBook.me plugin accepts payments

A. Ideally the client would like to get a commission on the transaction would this be possible with this set up?

B. If this is not possible could we set it up so that admin receives payment first then sends it on minus commission? If so how could we achieve this? 

> 3 . Do you offer a review system so clients could review the barbers?
> We are about to release customer review plugin very soon. you can have one for each Barber or have on Global review

That’s great, It is quite important for my client to have a review system on this so is this a promise I can make now and add it to the Barber’s page within the next few weeks?

Now we are able to have different “doors” on the customer’s side of the app would I be able to view their current bookings? Past bookings? Favourite Barbers?

Many thanks!
Rob

**Comment by DanielHindi** [comment]
1.A I dont think you can do that with YouCanBook.me Plugin however you certainly can with a custom plugin

1.B Yes but you'd need to develop that in their plugin using User Data https://github.com/BuildFire/sdk/wiki/User-Data:-Save-user-data-from-the-widget if you want this done from the app. IF you allow them access to the CP then this can happen out of the box.

2.A I think commissions or referral fees may need to go through YouCanBook.me or any other provider. So i'm not sure

2.B. I'm pretty sure you can do this with YouCanBook.me because you would be the merchant on file. However, you would need to distribute out the commissions

3.A I cant give you solid timelines on our development. However, I can tell you that that we are currently working on it

3.B Yes, If you go though YCB.me then they can see it their in their calendars. If you create your own plugin you can do that as well

Is summary, You probably need to go down 1 of two Paths:
Path A. You see what you have out of the box and model your business around it
Path B. invest in developing your own plugins (even if you fork our open source ones) and make the _app_ model around your business

**Comment by robbgreen** [comment]
Hi Daniel, 

Thanks for the info. Ok here's the score, I am not a developer, I am a designer and can only do css / html kinda stuff so a lot of this is well above me. Ideally I would like to make as much of this as I can and keep the costs down but if really needed then I would be willing to pay for a developed plugin. If you can point me in the right direction for this that would be great (you probably already have). I really appreciate your patience!

**The main points, functionality wise, for the app is to:**  
- Have to have two user login paths
- Allow Different functionality for each group of users

(1.) You mentioned before about user login paths: 

> if it is a secure fork meaning they would have to log in to be allowed into the Barber side you can do this several ways here are a couple of options
> 
> Fork the existing Folder Plug ( its open source in github ) And add in a White List of approved barber users into that section
> You can certainly develop your own plugin from scratch.
> You can look into using User tagging as a filtration mechanism

Do you think "Fork the existing Folder Plug" is the best way forward with this? If so are there any tutorials on how to achieve it. If not how much would I be looking at to get this done?

(2.) Allowing Different Functionality for each user group. You mentioned:

> Yes but you'd need to develop that in their plugin using User Data https://github.com/BuildFire/sdk/wiki/User-Data:-Save-user-data-from-the-widget if you want this done from the app. IF you allow them access to the CP then this can happen out of the box.

If I were to develop that in the plugin then can you point me to a tutorial on how to do it? In regards to allowing access to CP, would they have access to all the system or could we provide them a kind of window just to the elements each barber would need. Ideally I don't want to navigate the users outside the app, unless it were a web window within the app so it appears to still be within the app. What do you think is the best way forward with this? Again if it is too difficult how much would I be looking at to achieve it?

Thank you very much for you help with this!

Rob

**Comment by robbgreen** [comment]
Hi Daniel, 

Hope you're well.

Sorry just one additional question to my last mail:

(3.)  Is there a possibility to allow customers to select three booking slots and then for the barber to confirm one of these? (Reason being that barbers are quite busy usually so we need to have some kind of flexibility.) 

Many thanks, 

Rob

**Comment by DanielHindi** [comment]
I'm not sure with the booking integration services like YCB.me and Calendly you would need to check with them. If you end up developing a custom plugin then defiantly they can

**Comment by robbgreen** [comment]
Thanks Daniel, 

And what about question (1.) & (2.)?

Cheers!

**Comment by DanielHindi** [comment]
I guess for 1 and 2 you would need a developer to assist you. It would defiantly save you time. I had a rep reach out to you to find you the best solution. If he hasnt yet let me know I will ping him again.

**Comment by robbgreen** [comment]
Yeah I've now enlisted the help of a developer to help with this. Thanks for that, they tried to get through but my phone not working, I will reschedule the call though. 

Cheers,

Rob

**Comment by robbgreen** [comment]
Hi Daniel, 

This project is awaiting confirmation, thanks for your help with the logistics. 

I have another possible project which will be base on the functionality of 'Deliveroo' whereby customers can order a delivery service pay for it and will be given an countdown delivery time. Essentially it would be like using 'places' but flipped so users are given a delivery countdown time as apposed to how far away they are from the location. Would this be possible? 

Cheers!

Rob

**Comment by DanielHindi** [comment]
In general you can develop anything you want through custom plugins. Some limitations apply when accessing hardware on the device like NFC. However, those limitations are being removed one by one.
With custom plugins you can use as much as you like of our BuildFire services like DataStore, UserData, Auth, Push Notifications ...etc The part you would like to keep custom for yourself you can host and integrate with.

Good luck

**Comment by robbgreen** [comment]
Hi Daniel, 

Would it be possible for the app to share a database of it's barbers (info/Pic/Contact Details) with a website too? For example on the app you would be able to book individual barbers, you would also be able to do this on the website. I am trying to find a way which will eliminate admin having to upload new applications (barbers) to both app cms and web cms... Any thoughts?

Many thanks!

Rob

**Comment by DanielHindi** [comment]
If you develop your own database sure. You can have the plugin and the site pull from the same database api.
