### ISSUE TITLE
Follow up on view profile SDK

### ISSUE THREAD

**Issue by iamcmayers** [BuildFire/sdk#242]
At first, added SDK feature does not return link to profile.

It consists of next information (in brackets will be shown the example of values):
- ID ("000000000");
- Email ("dev@example.com")
- username ("dev@example.com")
- displayName (null in our case)

I've got data from requests profiler, because method callback returns null (though, this method is in beta)

Daniel Response:

Hey CJ, no you didnt . we created the api to fetch the profile data not show it. We are creating another api next to it that will use our core profile page to show the selected user profile. 

- Daniel from BuildFire

**Comment by ahabeb** [comment]
Hey @iamcmayers 
to navigate the app to the user profile you can use this method:
`buildfire.auth.openProfile(userId);`
for more info for this you can check [https://github.com/BuildFire/sdk/wiki/How-to-use-auth#buildfireauthopenprofileuserid](url)

and to get the user profile info, you can use this method:
`buildfire.auth.getUserProfile({userId:"XXX"},callback);`
for more info you can check [https://github.com/BuildFire/sdk/wiki/How-to-use-auth#buildfireauth-getuserprofileoptionscallback](url)
