### ISSUE TITLE
Follow up on ATOM RSS from shopify

### ISSUE THREAD

**Issue by iamcmayers** [BuildFire/sdk#243]
In analyzing your RSS feed, it seem your feed has been formatted as at ATOM feed. While our system does indeed work with a variety of RSS feeds, the preferred format is RSS 2.0, which has a specific image element incorporated into each feed entry. RSS 2.0 successfully pulls into our system, and displays the image in the indicated area. 

BuildFire supports Product integration from Shopify which works perfect now that we got that little issue fixed,  but the majority users who use shopify most likely use the shopify blog, it is ashamed we have to compromise the blog in this case because shopify uses ATOM and not ATOM 2, I've spoke with shopify they said they will not upgrade but maybe in the future. 

I wanted to know if buildfire has an alternative solution because the only issue the buildfire plugin is not pulling the the feature image.

**Comment by DanielHindi** [comment]
Hello @iamcmayers,
Do you have an example url we can test?

**Comment by iamcmayers** [comment]
Of course: https://www.girlswhopowerlift.com/blogs/blog.atom

**Comment by DanielHindi** [comment]
This is the result I get using Media Center RSS Feed
![image](https://cloud.githubusercontent.com/assets/492189/17497273/e587bfa4-5d75-11e6-8df1-72409a907ea9.png)

Are you saying the feed comes in but the images are not being pulled? 
If so it seems the Shopify is injecting content as HTML in CDATA
```
<content type="html">
      <![CDATA[ ...
```

Thats why feed reader doesnt pull images. Its a HTML block that could have anything in there. I hope this make sense ?

![image](https://cloud.githubusercontent.com/assets/492189/17497381/79265eaa-5d76-11e6-9dfb-e420a541b5ae.png)

**Comment by iamcmayers** [comment]
Correct, front image is not being pulled, but inside the blog images are being pulled.

**Comment by DanielHindi** [comment]
Correct because its not an Image element its a chunk of HTML that is taken in as one chunk and rendered on the details page. Basically Shopify isnt providing an image element.
The easiest course of action maybe to remove the images all together from the initial list. If that seems like a reasonable alternative I can send it over to the product team for consideration as a new feature.

**Comment by iamcmayers** [comment]
Ok I'm willing to accept that as an alternative method, for now ill disable blog plugin.

**Comment by DanielHindi** [comment]
I wish I had a better answer for you. I'll send it over.
