### ISSUE TITLE
home page design

### ISSUE THREAD

**Issue by alvintkb** [BuildFire/sdk#244]
![image](https://cloud.githubusercontent.com/assets/12888730/17577613/6b0b8fd2-5fb2-11e6-9d55-d53d7246d3e9.png)
I need to create home page with layout and style as above, please advice whether is it possible and how?

**Comment by DanielHindi** [comment]
Hello alvintkb,
Yes. you defiantly can do this either by creating your own custom plugin (https://github.com/buildfire/sdk/wiki) or fork and existing plugin like Folder (https://github.com/BuildFire/?utf8=%E2%9C%93&query=folder) .
If you are not technical you can contact our Pro Services department to connect you with a certified BuildFire developer.

Hope this helps

**Comment by alvintkb** [comment]
Dear Hindi.I know javascript programming and html very well, just need some guide from you on how to replace home page with custom plugin. cos I receive a project which your current home page can not achieved what i need. the layout is like above. please advice thanks.

Date: Thu, 11 Aug 2016 08:46:44 -0700

**Comment by DanielHindi** [comment]
I would start with reading about how to develop a custom plugin here 
https://www.youtube.com/watch?v=IZcvBZT-zjY&list=PLnq_waykAGlgsERwxHmGNokE6WIeVeH0I
and here
https://github.com/buildfire/sdk/wiki  
HTML, JS and CSS is defiantly enough information 
Once you create a simple plugin and get more comfortable with the platform you can begin developing the full plugin.

Once you're ready to test the plugin in the Control Panel and App (Emulator) you can upload your plugin as seen here https://www.youtube.com/watch?v=ZhFQsM4C1Zk&list=PLnq_waykAGlgsERwxHmGNokE6WIeVeH0I&index=3

Hope this helps

**Comment by alvintkb** [comment]
Dear Sir,Maybe I given you the wrong info, I just want to change the landed page, or main menu, my customer don't want the buildfire landed page, he want the design as something like the attachment, which currently can not achived by your layout and style function.

Date: Fri, 12 Aug 2016 08:49:57 -0700

**Comment by DanielHindi** [comment]
The image you provided is extremely small so its difficult to see what you are talking about. However, from what I gather. It sounds like you dont want to make UI changes via HTML,CSS and JS you want to do this from the Control Panel. The options available will be in 2 places:

![image](https://cloud.githubusercontent.com/assets/492189/17639789/b3e84cc4-60aa-11e6-854a-0ce4337c8dc8.png)

And the other is in the design section in the plugin

![image](https://cloud.githubusercontent.com/assets/492189/17639802/d927d900-60aa-11e6-8063-a1c9a5854397.png)

If you have trouble with any one of these you can contact customer support and they can walk you through it.

Any other options would either be from other plugins or making code changes. I hope this answers your questions

**Comment by alvintkb** [comment]
is it possible to duplicate a standard plugin and then modify?

Date: Fri, 12 Aug 2016 16:37:15 -0700

**Comment by alvintkb** [comment]
Dear Sir Hindi,is it possible to duplicate a standard plugin and then modify? I mean modi the javascript and html

From: alvintkb@hotmail.com
To: reply@reply.github.com; sdk@noreply.github.com
CC: author@noreply.github.com
Subject: RE: [BuildFire/sdk] home page design (#244)
Date: Sat, 13 Aug 2016 13:31:45 +0800




is it possible to duplicate a standard plugin and then modify?

Date: Fri, 12 Aug 2016 16:37:15 -0700

**Comment by alvintkb** [comment]
Dear Hindi, I try below code, is not working, did I code wrongly?<p><a href="appb4f1cd://plugin/4dd68723-2fa5-4579-90c5-13d1a4cc04f1-1471117708135">hello</a></p>

Date: Fri, 12 Aug 2016 16:37:15 -0700

**Comment by DanielHindi** [comment]
yes you can copy and modify existing plugins .. please see first reply 
"or fork and existing plugin like Folder (https://github.com/BuildFire/?utf8=%E2%9C%93&query=folder)" If you are unfamiliar with git forking this may help https://www.youtube.com/watch?v=f5grYMXbAV0

as for your deep link. If you are not trying the link on a mobile device with that custom schema installed it wont work

**Comment by alvintkb** [comment]
Dear Hindi,  I really appreciate your promt reply, can you advice me how to use one html button or hyper-link to call another plugin? I really need this function, please advice.

Date: Sat, 13 Aug 2016 19:19:26 -0700

**Comment by DanielHindi** [comment]
If you take a look at both Folder plugins they both show you how its done. The raw documentation is available here:

To navigate from one plugin to another withing the same app use:
https://github.com/BuildFire/sdk/wiki/How-to-use-Navigation#buildfirenavigationnavigateto-pluginid-instanceid-title

To make sure the referencing plugin has the freash data use:
https://github.com/BuildFire/sdk/wiki/How-to-use-the-Datastore-Dynamic-Data

example used in folder plugin https://github.com/BuildFire/folderPlugin/blob/f93088379e4163a9d6c4f013c733ee2e7c2ed37a/widget/widget.controller.js#L411
https://github.com/BuildFire/folderPlugin/blob/f93088379e4163a9d6c4f013c733ee2e7c2ed37a/widget/widget.controller.js#L487

**Comment by alvintkb** [comment]
Dear Hindi,
I try to use buildfire.navigation.navigateTo with below pluginsInfo, but it return invalid navigation request, please advice what wrong with below informatiopn.
pluginsInfo-------------------instanceId:"ba4139dd-09c6-4121-aa4a-c72570af07fc-1471214825754"pluginType:ObjectpluginTypeId:52refId:"ba4139dd-09c6-4121-aa4a-c72570af07fc-1471214825754"title:"MENU"token:"ba4139dd-09c6-4121-aa4a-c72570af07fc"__proto__:Object.id:"57b0f4e2475a7e5a05f33fd9"


buildfire.navigation.navigateTo ("57b0f4e2475a7e5a05f33fd9", "ba4139dd-09c6-4121-aa4a-c72570af07fc-1471214825754", "MENU")buildfire.js:168 invalid navigation request  57b0f4e2475a7e5a05f33fd9

**Comment by DanielHindi** [comment]
Every plugin has certain data that is potentially changing such as tokens, titles, icons ...etc
So if you have any hard coded values these will likely fail. If you are saving these values in your plugin these will likely fail or become stale soon after. Best thing to do is use Dynamic as referenced above

> To make sure the referencing plugin has the fresh data use:
> https://github.com/BuildFire/sdk/wiki/How-to-use-the-Datastore-Dynamic-Data

*Scenario: *
Lets say your launcher plugin (the plugin you are developing to open up another plugin) references Plugin A.
Plugin A has the following data:
Token: 1111-1111-1111
Icon: apple.png
Title: Apple Sale

If you save all this information in your Launcher Plugin and anything changes you will be in 1 or 2 states
a. If what changed isnt critical like icon or title then your reference data is stale and it will be confusing to the user
b. if it is critical like tokens then the navigation will break

This is why using dynamic data is so important it will always give you the latest plugin data. all you need to save is the reference id that never changes
