### ISSUE TITLE
Is there any way to send an attachment in sendMail action Item ?

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/sdk#245]
https://github.com/BuildFire/sdk/wiki/How-to-use-action-Items

**Comment by DanielHindi** [comment]
Currently no. The best way is to have a link in the body to download the file.

**Comment by vineetasharma** [comment]
@DanielHindi  Thanks for alternate solution. But currently, If we provide the html in body then it read as string not html. Please tell me how i can send html as email body?
