### ISSUE TITLE
Numeric keyboard iOS

### ISSUE THREAD

**Issue by waltergrio** [BuildFire/sdk#247]
We have a field where we want to launch the standard numeric keyboard (0-9, decimal, backspace) but it's not working on iOS.  Any advice would be greatly appreciated!

**Comment by DanielHindi** [comment]
Have you changed the input type to <input type="number"> ?

**Comment by waltergrio** [comment]
We're able to launch an iOS keyboard with numbers at the top, but it's still a full keyboard with the other characters.  What should our type be to launch just the numeric keyboard without the other characters?  By the way, on Android it works fine.  Thanks!

**Comment by DanielHindi** [comment]
Haver you tried this? http://blog.pamelafox.org/2012/05/triggering-numeric-keyboards-with-html5.html

<input type="text" pattern="[0-9]*">

**Comment by waltergrio** [comment]
Yes, we're on the 3rd scenario.  We haven't figured out how to get the numerical keypad (numbers only) to work on both iOS and Android.  Just as in that blog, it's one or the other.
