### ISSUE TITLE
On buildfire.datastore.get api throws unhandled packet error sometime and content view scattered

### ISSUE THREAD

**Issue by sandeepchhapola** [BuildFire/sdk#25]
![unhandled packet](https://cloud.githubusercontent.com/assets/7790671/8904313/d8389b26-347b-11e5-9113-125a82d0e1f6.png)

**Comment by DanielHindi** [comment]
this is just a warning meant for tracing this is normal

On Mon, Jul 27, 2015 at 3:54 AM, Sandeep Chhapola <notifications@github.com>
wrote:

> [image: unhandled packet]
> <https://cloud.githubusercontent.com/assets/7790671/8904313/d8389b26-347b-11e5-9113-125a82d0e1f6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BuildFire/sdk/issues/25>.
>



-- 

*Daniel Hindi | Chief Technology Officer and CEO*

*Phone:* 1-619-786-0778

*Skype: *daniel_hindi

*Website:* MadainCorp.com
