### ISSUE TITLE
Loyalty Plug In Points

### ISSUE THREAD

**Issue by liquorifit** [BuildFire/sdk#252]
Hi, I have set up the commerce and loyalty plug ins to my app but thought that purchases from the online store within the app would automatically add points to the user's account when something was purchased through the app. (like the X points per purchase and the X points per dollar spent) Then whenever needed to award extra points in person, the option to add is there.

Someone through support directed me to ask how to link that in a custom plug in here. I made a great custom store plug in that acted as a store with custom text and buy buttons with product price and image included. How can I connect the e-commerce app or my custom store plug in to the loyalty plug in? Or do I also need to make a custom loyalty plug in that links with my custom store plug in?

Thank you!!

**Comment by DanielHindi** [comment]
Just so I understand. You have the standard [Loyalty plugin](https://github.com/BuildFire/loyaltyPlugin) and you want it to automatically add points when that same user has purchased an item from your store.

If that is they case, can this be passive? ie you can fork the loyalty plugin and make it check your commerce api to see if there are any pending points waiting and add it in right there and then for them. So when the loyalty plugin opens, take the user token or the user email and call your api, it will return a number of points (or something like that) then you can add it directly to them

If you dont want to wait until they open the plugin, you can create a [BuildFire Service](https://github.com/BuildFire/sdk/wiki/BuildFire-Widget-Services) and this will trigger when the app start. you can then give a congrats message and navigate to the loyalty plugin
