### ISSUE TITLE
Input on Text Field Causes Problems

### ISSUE THREAD

**Issue by waltergrio** [BuildFire/sdk#254]
We have a Notes field where users can enter notes.

We are having issues on iOS when users enter text in a text field.  Entering it once seems ok, but if you try to update the existing text, it doesn't do anything and sometimes the app will crash.

**Comment by waltergrio** [comment]
More specifically -- if you enter some text, it's ok.  When you edit it by placing the cursor on a word, it's ok.  However, if you try to move the cursor to another word, the keypad is still there but you can't type anything.

**Comment by abuturla** [comment]
@waltergrio Thanks for reporting the issue. We've been able to reproduce it on our end and are looking into a fix. I'll let you know when we have an update.

**Comment by waltergrio** [comment]
Thanks @abuturla.  It's a critical issue for me as my app relies heavily on users inputting data via text fields.

**Comment by waltergrio** [comment]
Just FYI, it seems like it works ok when I use the app.buildfire.com link and using Safari on my iPhone vs when I use Buildfire Previewer.  Do you think this is just an issue with Buildfire Previewer?  Or will it also happen when I publish the app?

**Comment by abuturla** [comment]
@waltergrio This issue will occur in an app (and the previewer) but not in a standard web browser. We've identified a potential fix, and will be working on implementing it soon.

**Comment by waltergrio** [comment]
@abuturla thanks so much for the info and the update.  I really appreciate it!

**Comment by waltergrio** [comment]
Hi @abuturla - I just wanted to find out if you think this will be done this week so we can apply to our app.  If not, I may need to adjust my release date.  Thanks!

**Comment by abuturla** [comment]
@waltergrio We have it in our queue, but unfortunately I don't know when it will be delivered. Most likely it will not be available this week. I'll be sure to keep you up to date with any new developments.

**Comment by waltergrio** [comment]
Hi @abuturla - do you think it will be done before October?

**Comment by abuturla** [comment]
Hi @waltergrio. Unfortunately our team has been side tracked with some high priority items. The issue is still on our radar. I will bring it up with the team again today.

**Comment by waltergrio** [comment]
Hi @abuturla - any new updates?  This issue is preventing me to go-live unfortunately.  What's the earliest timeframe this could be fixed?  Thanks.

**Comment by mkuhnsbuildfire** [comment]
Hi @waltergrio,
We have identified a possible solution to this issue. I am still researching this one and hope that we can get something out by Friday. I'll let you know if something sidetracks us, so we can't have this fixed by then.

**Comment by waltergrio** [comment]
Thanks @mkuhnsbuildfire!

**Comment by mkuhnsbuildfire** [comment]
Hi,
We have a fix for this, but it will take just a bit longer for us to fix this. I wish this was a little more trivial that it seems. I will have an update for you on Monday.
Thanks for your patience on this one.

**Comment by waltergrio** [comment]
Thanks for the update @mkuhnsbuildfire.  Look forward to hearing more on Monday.

**Comment by mkuhnsbuildfire** [comment]
Hi @waltergrio,
I'll be deploying a change tomorrow that addresses this issue. I'll let you know if anything changes.
Thanks

**Comment by waltergrio** [comment]
hi @mkuhnsbuildfire, just checking to see if it was deployed.  Thanks!

**Comment by mkuhnsbuildfire** [comment]
Hi,
I deployed a partial fix yesterday. Text boxes should be able to be edited. Are you using a custom plugin with text? Let me know if you see improvement in the inputs.
Thanks

**Comment by waltergrio** [comment]
Thanks @mkuhnsbuildfire - yes we're using a custom plugin that takes text.  Will keep you posted!  Thanks!

**Comment by waltergrio** [comment]
@mkuhnsbuildfire - just to confirm, we don't actually have to do any code changes on our end?  It looks like it's working better as I'm testing it in BF Previewer.

**Comment by mkuhnsbuildfire** [comment]
Ok, sounds good, please let me know how your testing goes ...

**Comment by waltergrio** [comment]
Seems to be working fine on BF Previewer.   Will let you know if I see issues later on.  Thanks!
