### ISSUE TITLE
Exporting Data

### ISSUE THREAD

**Issue by waltergrio** [BuildFire/sdk#256]
Is it possible to export data so that it can be emailed to the user either via HTML, text within the body of the email, or a CSV file?

**Comment by DanielHindi** [comment]
You should be able to pull the data and use the html "mailto:" link builder
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Email_links

**Comment by waltergrio** [comment]
@DanielHindi - we can pull the data and launch an email client, but the HTML inside the body is not being read as HTML.  It's just reading it as text / string.

In short, I'd like to create a table inside the body of the email.  Is this possible with Buildfire?

**Comment by DanielHindi** [comment]
You can try using something like this:
````
var formattedBody = "FirstLine \n Second Line \n Third Line";
var mailToLink = "mailto:x@y.com?body=" + encodeURIComponent(formattedBody);
window.location.href = mailToLink;
````
ref: http://stackoverflow.com/questions/5620324/mailto-with-html-body

but you want to be careful there are limitations:
http://kb.mailchimp.com/campaigns/design/limitations-of-html-email

**Comment by waltergrio** [comment]
Thanks Daniel.  We'll check it out!
