### ISSUE TITLE
User Import

### ISSUE THREAD

**Issue by dosjots** [BuildFire/sdk#257]
Hi,

Would like to import a list of users into my application.  No externally facing feature exists but there must be a way to accomplish this? 

Thanks,

jason

**Comment by DanielHindi** [comment]
In the Control Panel you can do an import

![image](https://cloud.githubusercontent.com/assets/492189/18364759/5c21d3fa-75c4-11e6-9707-50b246a34e6c.png)

**Comment by dosjots** [comment]
Hi, Tried that and if the user exists, no problem.  But if the user does not exist, i'm getting an error message.  I'm trying to register 100-200 users who have never logged in.

**Comment by DanielHindi** [comment]
Ah understood. Unfortunately, you cannot do a bulk insert at this point. It is on our roadmap however I dont have a definitive timeframe for it. we will announce it on our @buildfirejs twitter feed when its out
