### ISSUE TITLE
Android back button always navigate to home no matter where you are in the app

### ISSUE THREAD

**Issue by snelson112** [BuildFire/sdk#258]
The android back button does not work with the app's onBackButtonClick event handler.  I added some custom logic within my plugin's controller.js to verify the back button is indeed hooked into the device's back button.  

I'm using the following code:

` var goBack = buildfire.navigation.onBackButtonClick ;
                buildfire.navigation.onBackButtonClick = function(){
                    console.log('custom back function triggered');
                }`

Now when I run this in the app, the plugin back function does not work which is expected but, the Android back button sends me to the Home plugin no matter where I'm at within the previous plugin. Am I missing something here?

**Comment by DanielHindi** [comment]
Hello snelson112,
We took a look into it. You are right. This isnt immediately apparent. However, we were able to reproduce. We will look into a fix asap. We will keep you posted here

**Comment by snelson112** [comment]
Thanks Daniel, I appreciate the quick response!  We plan to go live with our app before October so we're really hoping to have the issue fixed before then. Thank you!

**Comment by DanielHindi** [comment]
Hey Sherwin,
Just wanted to updated you. I pinged the team on this again today. Got side tracked with some high priority items. This is still on our radar.

**Comment by snelson112** [comment]
Thanks for the update Daniel! Our go live is about 2 weeks out so please do keep us posted on the progress, thanks again!

**Comment by mkuhnsbuildfire** [comment]
We have just deployed a fix for this and tested it. Please let us know if this addresses your issue. I'll leave this issue open until Friday September 30, 2016.

**Comment by snelson112** [comment]
Thanks Matt/Daniel, the back button now works on our Android devices, we will continue testing this week and get back to you guys with any issues, thank you so much!
