### ISSUE TITLE
Error with buildfire.imageLib.showDialog when i tried to use it it throws Uncaught TypeError: window.openDialog is not a function error

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#26]
```js
buildfire.imageLib.showDialog({showIcons: false, multiSelection: false},
                function (error, result) {
                    if (result && result.selectedFiles && result.selectedFiles.length > 0) {
                        $scope.data.content.bgURL = result.selectedFiles[0];
                        $scope.$apply();
       }
 });
```
![buildfire imagelib showdialog](https://cloud.githubusercontent.com/assets/7682731/8904475/4e8aa142-347d-11e5-8bf5-d0c9d79bb318.png)

**Comment by DanielHindi** [comment]
duplicate ticket https://github.com/BuildFire/sdk/issues/24

**Comment by deepakshrma** [comment]
actually both have different error that is why i logged it differently.

**Comment by DanielHindi** [comment]
same root, but all being resolved today

**Comment by deepakshrma** [comment]
https://github.com/BuildFire/sdk/wiki/How-to-use-ImageLib#buildfireimagelibshowdialogoptions-callback

works fine for me!! Bingoi!!
