### ISSUE TITLE
Custom Login & Deep Link Issue With iOS

### ISSUE THREAD

**Issue by liquorifit** [BuildFire/sdk#262]
Hi,

I have been working on a simple custom plug in that is a login form that when my personal training clients login to a username and password that I gave them and set up, they are forwarded to a Text Plug In that has their training program, meal plan and any news I'll update daily. I got it all set up, published my app's changes and the custom login plugin worked perfectly on an android device but from an iPhone, it doesn't send the user to their page or any page. It's just an iOS issue and I'd love a clarification how I can make this simple set up work right. Thanks! I'll attach pictures of some of my code to see if you can spot out a bug.

![screen shot 2016-09-25 at 1 24 29 pm](https://cloud.githubusercontent.com/assets/21693713/18817016/9cbc51d0-8323-11e6-8ce4-4c4b0743de61.png)
![screen shot 2016-09-25 at 1 24 17 pm](https://cloud.githubusercontent.com/assets/21693713/18817015/9cbc2b1a-8323-11e6-8741-dc514add5817.png)
![screen shot 2016-09-25 at 1 23 59 pm](https://cloud.githubusercontent.com/assets/21693713/18817017/9cbfe03e-8323-11e6-9317-a7622b321099.png)

**Comment by rAbdelHadi** [comment]
Hi Liquorfit , 

What you are trying to do can't be through using the custom plugin , you need to create your own custom plugin and start learning how to use the buildfire sdk. 

Here are some good links where you can start with :

1- http://buildfire.com/developers/
2-https://github.com/BuildFire/sdk/wiki

Also you can check the folder plugin to understand how you can navigate to other plugin from your custom plugin  (https://github.com/BuildFire/folderPlugin)

Check the following link for the highlighted code snippet which help you to understand how you can call the buildfire sdk to navigate to other plugins within the app.

https://github.com/BuildFire/folderPlugin/blob/09d11fc2364116a06b31a3089db965977402b821/widget/widget.controller.js#L490-L494 

Here are some good information about the navigation functionality within the buildfire sdk (https://github.com/BuildFire/sdk/wiki/How-to-use-Navigation)

Thanks.
