### ISSUE TITLE
Android Back Button (Side Menu)

### ISSUE THREAD

**Issue by waltergrio** [BuildFire/sdk#263]
When a user is on the Side Menu and clicks on the Android Back button, it takes them out of the app (i.e. minimizes it).  Is this by design or should it just close the Side Menu?  Also, is it possible to replace the "X" on the top right of the Side Menu to say "Close" or "Cancel"?

**Comment by mkuhnsbuildfire** [comment]
Hi,
I am supposing that you are on the home plugin when you open the side menu, then hit back. The functionality is when you are on the home plugin and you hit the back button, it exits the app. The side menu is not considered a plugin. 
I can discuss with the team about replacing the "X." We would have to change the styling as the word "Cancel" is wider in pixels. The "X" button is universally accepted as close.

**Comment by waltergrio** [comment]
Thanks @mkuhnsbuildfire.  I think if they hit the Android back button while they're on the Side Menu, it shouldn't close the app or minimize it.  That would be my enhancement request instead.  Thanks.
