### ISSUE TITLE
Download of the Plugin

### ISSUE THREAD

**Issue by axelscosta** [BuildFire/sdk#269]
Hi!

I have uploaded in the buildfire developer portal a plugin, with my account: alexandre.costa@2giveweb.pt . That version that i've uploaded is really precious, it's my safe backup because i've messed up with what I have right now. How can I download what I've uploaded?

Thanks in advance

**Comment by DanielHindi** [comment]
There isnt a super easy way for you to do that. We can do that for you on the back end we can send the zip file to alexandre.costa@2giveweb.pt 
However, its always good to have two copies in the Dev Portal (QA and Prod) 

I'll open up an internal ticket for you to get that copy

**Comment by DanielHindi** [comment]
There are several plugins under that account. Can you tell me which plugin you need?

**Comment by axelscosta** [comment]
Hi! Thanks for the fast reply.

Here is the plugin:

*BBom Messenger v4.1.3 (there is alot of duplicates, there was some kind of
lag when creating licenses.)*
Also, if possible send it to: alexandre.costa@pc4d.pt , since our company
does not use 2giveweb emails anymore.

Thanks for the help! This plugin is a Whats App "clone" that we are doing.
I would love to get buildfire feedback when finished! :) Any info on the
buildfire future marketplace?



2016-10-20 21:21 GMT+01:00 Daniel Hindi <notifications@github.com>:

**Comment by axelscosta** [comment]
Hi!

Any updates on this? I'm a bit behind schedule.


2016-10-21 10:06 GMT+01:00 batido verde <alexandredasilvacostapt@gmail.com>:

**Comment by abuturla** [comment]
@axelscosta We'll have this for you tomorrow.

**Comment by abuturla** [comment]
@axelscosta For security purposes we can only send the plugin code to the plugin author. I have emailed the code to the address specified by the plugin author. Thanks.

**Comment by axelscosta** [comment]
Ok, haven't received anything yet. Send the file again: alexandre.costa@2giveweb.pt , i've re-activated the account.

Thanks!

**Comment by abuturla** [comment]
@axelscosta We have a different email address listed for the plugin author.

**Comment by axelscosta** [comment]
Ok, I finally understand the course of this discussion.

![captura de ecra 2016-10-26 as 23 30 35](https://cloud.githubusercontent.com/assets/22841716/19747553/4a82b8fe-9bd4-11e6-947b-8d51e8bb9a99.png)

Yes, it's this one, we do know. I didn't upload the project to that dev account though right? The plugin is in 2giveweb's account. So please do tell me, what are you doing at all?

**Never, EVER, send a plugin from my company's account to a personal email, without me approving.** I left it this way for company personal reasons, that do not matter to buildfire. Also, you could have sent to felipe.silva@pc4d.pt or felipe.silva@2giveweb.pt , but never to personal emails outside of our company / dev account. Thankfully, that email is fake, but imagine it was not? Imagine that the developer we hired, is no longer working on this, but instead, a whole different team? Now he could have had all the work we are doing for months. 

You went out of your mind with this one.

**Comment by DanielHindi** [comment]
Hello axelscosta,

Please understand we do not facilitate code management, so we dont get into these misunderstanding. When you asked  "How can I download what I've uploaded?" we could have said sorry we do not have a way to do this. Which is our Official Answer. It was my mistake to try to go through the back end to help. Unfortunately we will not be sending a copy to any developer.
