### ISSUE TITLE
Getting Started Geolocation

### ISSUE THREAD

**Issue by nsimauko** [BuildFire/sdk#272]
Hello Friend,

I am new here and not a pro with programming. But am good with CSS and HTML. I am trying to build an app that would know via geo location where a certain user is. Just like that you have on uber. knowing where a person is at a certain time. 

I would like help in setting this up to fully work on iOS and Android.
Regards,
Nsi

**Comment by DanielHindi** [comment]
Hello Nsi,

Its pretty simple. here is an example that checks for sensitive changes in location and reports back the new position so you dont have to constantly ask for the location every few seconds.
```
buildfire.geo.watchPosition(	{ enableHighAccuracy: true , timeout:30000}
	, function (position) {
			console.log('Latitude: '  , position.coords.latitude
					, 'Longitude: ', position.coords.longitude );
} );
```

Here is the [official documentation](https://github.com/BuildFire/sdk/wiki/BuildFire-Geo-Location-Feature)

This is a super [simple example](https://github.com/BuildFire/simpleBuildFireJSExamples/blob/master/exampleGPSTracker/widget/index.html) on how to get the devices location


Good luck

**Comment by nsimauko** [comment]
Dear Daniel,

Thanks do much for your response. As i mentioned earlier, i am new to mobile apps. I handle mostly website projects. Thus i have a client i need to setup a mobile app for to handle the following features:

1. The App would monitor technicians location and available to accept a job posted on the app.
2. I have seen some templates to choose from, but how do i get these things working on it, like customizing the template.
3.I want user(technicians) to register and login
4. users when logged in can see list of available jobs that have been posted on the app.
5. Users location is displayed.
6. User can accept job and can see the location of the job
7. User can get SMS or email notification when a job is posted on the app.

8. Admin can see all registered users
9. Admin can see users and respond based on location of user and if close to location of job posting.
10 Admin can post new jobs to registered technicians
11. On the user's end there should be a pop-up on the app to indicate a new job posting.

How do i begin with this. Would i need to hire a develoer.? Though i have good knowledge with HTML and CSS.

Thanks. Can i add you on Skype for further talks.?
Nsi

**Comment by DanielHindi** [comment]
Hello NSI,

This might involve a little more custom work that is totally doable. I would suggest contacting ProServices@buildfire.com they should be able to setup a call to better understand your needs and point you to the resources you may need to accomplish these tasks.

Best of luck

**Comment by nsimauko** [comment]
Dear Daniel,

Thanks for your email. I would contact them for further advice.

Regards,

**Comment by DanielHindi** [comment]
I also gave them a heads-up that you would be contacting them. Good Luck

**Comment by nsimauko** [comment]
thanks and i hope it would not be too expensive for me.

**Comment by DanielHindi** [comment]
They will give you multiple options and you can always find a developer on your own with in a comfortable price range (if needed) anyone can create a free dev account and you dont need any special skills to develop on our platform see https://www.youtube.com/watch?v=IZcvBZT-zjY&list=PLnq_waykAGlgsERwxHmGNokE6WIeVeH0I
