### ISSUE TITLE
error when updating plugin: Upload unsuccessful. Missing image.png in resources folder.

### ISSUE THREAD

**Issue by alandenison** [BuildFire/sdk#275]
Currently, I am trying to update an existing plugin, but I get an error while updating it.

My app information is:
App ID: 2b142986-955d-11e6-8a24-067ad0e445f5 with the default "Hello World" name.

I was successfully able to upload a previous version of the plugin and update that version. Today however, i am getting this error when I try to upload an update:
Upload unsuccessful. Missing image.png in resources folder.

It is saying the image.png is missing, however this file seems to be present. It is the default image that came with the SDK, and it is the same image that was originally uploaded.

I was wondering how I could get around this error.

Thanks,
Alan Denison

**Comment by DanielHindi** [comment]
does your zip file structure mimic this?

![image](https://cloud.githubusercontent.com/assets/492189/19822987/205db838-9d1b-11e6-8e16-6bd83d5b61da.png)

**Comment by alandenison** [comment]
Yes it does. I did have some extra media in the resources folder which i removed, and I still got that message

**Comment by rAbdelHadi** [comment]
Can you attach an example of the zipped folder which you are trying to upload and it fails ?

**Comment by alandenison** [comment]
[myPlugin.zip](https://github.com/BuildFire/sdk/files/562378/myPlugin.zip)
Here you go, thanks.

**Comment by rAbdelHadi** [comment]
It seems working fine and the plugin got updated successfully

**Comment by alandenison** [comment]
ok thanks for taking a look
