### ISSUE TITLE
aeondata APP

### ISSUE THREAD

**Issue by Michaelaeon** [BuildFire/sdk#278]
Hello, 
my App is just released today on the google play store. And in Apple Store in few weeks.
The Shop button and the e-commerce website from shopify, was exactly what i needed.
Nevertheless, i need one more plugin that could be vital to my business and communication.

I need a PLUGIN from where **we can insert a gift card code**, 
and that makes the registration with SHOPIFY.

Please contact me the sooner, i really need this functionnality.
Otherwise, the result of the app with Buildfire, was exactly what i was looking for.

isak sulaj
mw.aeondata@gmail.com

**Comment by DanielHindi** [comment]
Contacted via email
