### ISSUE TITLE
How to get list of the item that are inserted in same tag-name using buildfire.datastore.insert method ?

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#28]

**Comment by DanielHindi** [comment]
https://github.com/BuildFire/sdk/wiki/How-to-use-Datastore#buildfiredatastoreupdateidobj-tag-optional-callback

Notice there is an optional argument that is [TAG]

buildfire.datastore.update(id,obj, tag, callback)

**Comment by sandeepchhapola** [comment]
Hi Daniel,
Still, there is an issue related to fetching list of the item that are inserted in same tag-name using buildfire.datastore.insert method. For example, I have inserted some record using buildfire.datastore.insert as:

 function addContactRecord(contact){
                    buildfire.datastore.insert(contact, 'contactInfo',false,function(err,data){
                        if(err)
                            console.error('there was a problem saving your data');
                        else
                            console.error( contact.name + ' saved successfully');
                    });
                }

                addContactRecord ( {name:"sandeep", tel:"555-111-1111"} );
                addContactRecord ( {name:"kumod", tel:"555-111-1111"} );
                addContactRecord ( {name:"rahim", tel:"555-111-1111"} );
                addContactRecord ( {name:"John Doe", tel:"555-111-1111"} );
                addContactRecord ( {name:"Doe Jane", tel:"555-222-2222"} );

After that I have run buildfire.datastore.search to fetch the inserted data as: 

 var searchOptions={
                    /* "filter":{"$json.name":"Jane Doe"},*/ //Is it necessary to fetch inserted data? if necessary then what params I need to paas in filter object? 
                    "sort":{"field":"name","desc":true},
                    "page":"0",
                    "pageSize":"5"
                };

                buildfire.datastore.search( searchOptions , 'contactInfo',function(err,records){
                    if(err)
                        console.error('there was a problem retrieving your data');
                    else {
                        console.error('found ' + records.length + ' record(s)',records);
                    }
                });

And it returns empty array of records (records.length  is 0). Is there anything that I have missed?

**Comment by deepakshrma** [comment]
```js
//insert
buildfire.datastore.insert({"firstName":"Laura","lastName":"Bascoe"},'names2', function(){
    $scope.status='imported ' + data.length + ' names.';
    $scope.$apply();
});

//search
function search() {
    var pattern = '/*';
    buildfire.datastore.search({
        filter:{"$json.firstName":{"$regex":filter}}
        ,page:0
        ,pageSize:pageSize + 1 // the plus one is to check if there are any more
    },'names2',function(err,results) {
        console.log("Data:",results)
    });

}
search();
```

works fine for me.
