### ISSUE TITLE
Facebook Analytics

### ISSUE THREAD

**Issue by arc0489** [BuildFire/sdk#281]
Hi, I was wondering how to link the app to Facebook's app analytics

**Comment by liquorifit** [comment]
Hm I was wondering the same thing

**Comment by mkuhnsbuildfire** [comment]
We have segment (https://segment.com/) available to collect data. You can create an account and then feed your data over to Facebook app analytics.

**Comment by liquorifit** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } How do I feed the data over to Facebook??


Sent from Yahoo Mail for iPhone


On Monday, November 28, 2016, 7:18 PM, Matt Kuhns <notifications@github.com> wrote:


We have segment (https://segment.com/) available to collect data. You can create an account and then feed your data over to Facebook app analytics.

**Comment by bkalaldeh** [comment]
It is currently not possible to link to Facebook app analytics from your app Segment account. 

Supported integrations must have the 'Server' source option under 'Sources' section on the integration page and Facebook app integration does not allow that yet:

https://segment.com/integrations/facebook-app-events

**Comment by DanielHindi** [comment]
closed due to inactivity
