### ISSUE TITLE
Getting analytics through Google Analytics & Segment

### ISSUE THREAD

**Issue by liquorifit** [BuildFire/sdk#282]
Hi.

I've linked my google analytics as an integration with segment and I have segment linked to my App but the analytics on segment are not specific (like which plugins are being opened, etc.) and it looks like google analytics is not getting a lot of info sent over.

In segment, under debugger, it lists every 'event' that happens on my app but doesn't get organized at all. 

I want to know how many times people download my app, open my app, open a plugin and their navigation around my app. I know its possible. 

Have any advice/instructions? (Please don't link me to that god awful buildfire university video talking just about minor details only referring to the reseller's analytics side)

Thanks!

**Comment by mkuhnsbuildfire** [comment]
I'll see what other details I can get you.

**Comment by bkalaldeh** [comment]
You should be able to see a summary view of the analytics pushed on google analytics:
https://support.google.com/analytics/answer/1010052?hl=en&ref_topic=1009682
https://support.google.com/analytics/answer/1010054?hl=en&ref_topic=1009682

And if you are developing a plugin you can add your own events using JS as explained here:
https://github.com/BuildFire/sdk/wiki/How-to-capture-Analytics-for-your-plugin

**Comment by DanielHindi** [comment]
closed due to inactivity
