### ISSUE TITLE
How to get Login Credentials

### ISSUE THREAD

**Issue by 3DT** [BuildFire/sdk#285]
I am new to buildfire and need some guidance please. Please advise the following:
1. Assuming I check-off for “Home” that the user must log-in.
a. How do I capture the users login name and keep it in a global variable? (We need this value when we call various external API’s)
2. I really am not proficient at JavaScript, since I will need to create/modify various plugins, what tool do you suggest I use.
Best regards, 
Larry Hurwitz

**Comment by DanielHindi** [comment]
Hello 3DT,

1.  To access the logged in user profile just use `buildfire.auth.getCurrentUser(callback);`
https://github.com/BuildFire/sdk/wiki/How-to-use-Auth
2. You should be able to use any Web IDE you're comfortable with. New comers usually like simpler tools like Brackets (http://brackets.io/)  more advanced developers like WebStorm Eclipse or Visual Studio. 

Hope this helps

**Comment by 3DT** [comment]
DanielYou are a gentleman, thank you!Larry


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Daniel Hindi <notifications@github.com> Date: 2016/12/13  21:41  (GMT+02:00) To: BuildFire/sdk <sdk@noreply.github.com> Cc: Larry <larryhsa@gmail.com>, Author <author@noreply.github.com> Subject: Re: [BuildFire/sdk] How to get Login Credentials (#285) 
Hello 3DT,

To access the logged in user profile just use buildfire.auth.getCurrentUser(callback);

https://github.com/BuildFire/sdk/wiki/How-to-use-Auth
You should be able to use any Web IDE you're comfortable with. New comers usually like simpler tools like Brackets (http://brackets.io/)  more advanced developers like WebStorm Eclipse or Visual Studio.

Hope this helps

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BuildFire/sdk","title":"BuildFire/sdk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BuildFire/sdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielHindi in #285: Hello 3DT,\r\n\r\n1.  To access the logged in user profile just use `buildfire.auth.getCurrentUser(callback);`\r\nhttps://github.com/BuildFire/sdk/wiki/How-to-use-Auth\r\n2. You should be able to use any Web IDE you're comfortable with. New comers usually like simpler tools like Brackets (http://brackets.io/)  more advanced developers like WebStorm Eclipse or Visual Studio. \r\n\r\nHope this helps\r\n"}],"action":{"name":"View Issue","url":"https://github.com/BuildFire/sdk/issues/285#issuecomment-266840352"}}}

**Comment by 3DT** [comment]
Hi Daniel Hopefully you can help/guide me here please.As the user logs into our app I would like to capture his exact location (long/lat) and continously get their long and long.This information I will be doing a https POST to our servers.Please advise how I would do this?Then lastly how would I force the location to update our server even if the user closes the app?Thanks Larry 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Daniel Hindi <notifications@github.com> Date: 2016/12/13  21:41  (GMT+02:00) To: BuildFire/sdk <sdk@noreply.github.com> Cc: Larry <larryhsa@gmail.com>, Author <author@noreply.github.com> Subject: Re: [BuildFire/sdk] How to get Login Credentials (#285) 
Hello 3DT,

To access the logged in user profile just use buildfire.auth.getCurrentUser(callback);

https://github.com/BuildFire/sdk/wiki/How-to-use-Auth
You should be able to use any Web IDE you're comfortable with. New comers usually like simpler tools like Brackets (http://brackets.io/)  more advanced developers like WebStorm Eclipse or Visual Studio.

Hope this helps

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BuildFire/sdk","title":"BuildFire/sdk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BuildFire/sdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielHindi in #285: Hello 3DT,\r\n\r\n1.  To access the logged in user profile just use `buildfire.auth.getCurrentUser(callback);`\r\nhttps://github.com/BuildFire/sdk/wiki/How-to-use-Auth\r\n2. You should be able to use any Web IDE you're comfortable with. New comers usually like simpler tools like Brackets (http://brackets.io/)  more advanced developers like WebStorm Eclipse or Visual Studio. \r\n\r\nHope this helps\r\n"}],"action":{"name":"View Issue","url":"https://github.com/BuildFire/sdk/issues/285#issuecomment-266840352"}}}

**Comment by NancyHaddad** [comment]
Hello Larry,
Sorry for the late response we have been out of the office for the holidays. Please follow this thread as we have provided some helpful information to move you forward on our platform. 

https://github.com/BuildFire/sdk/issues/296

For future reference, if you can please create a new ticket for new information you are seeking. This will help us and other developers using our platform. 

Thank you so much and happy holidays!
