### ISSUE TITLE
css asset file isn't loaded in iOS previewer

### ISSUE THREAD

**Issue by noahmiller** [BuildFire/sdk#289]
A stylesheet linked in the head of my plugin widget's index.html is loading properly in local testing and in the app.buildfire.com web GUI, but is not loading in the iOS previewer app.  In debugging using weinre, the stylesheet appears not to have been loaded at all.

Here's a snippet from index.html:

```html
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="assets/css/radioPlayer.css" rel="stylesheet">
   <script src="../../../scripts/buildfire.js"></script>
   <script src="assets/js/radioPlayer.js"></script>
</head>
```

What might be wrong?

**Comment by mkuhnsbuildfire** [comment]
Hi,
I'm wondering if the path might be wrong. What does your file structure look like?
Thanks

**Comment by noahmiller** [comment]
The path works fine in local testing and in the BuildFire web GUI.  Here's the plugin directory structure:

<img width="176" alt="radio plugin directory structure" src="https://cloud.githubusercontent.com/assets/117264/21364947/0ca4cec4-c6c1-11e6-8ce7-b94c0507ea67.png">

**Comment by DanielHindi** [comment]
Can you attach your app Id and plugin name so we can check for you

**Comment by noahmiller** [comment]
Thanks Daniel.

App id from control panel for the Radio Ha-Ha! app: cae968ad-9fa0-11e6-8a24-067ad0e445f5
App id (?) from my dev account: 20ccff06-c3b9-11e6-adc3-124a75f7ddd1
Plugin name: "Radio Ha-Ha! Player"

**Comment by DanielHindi** [comment]
If you use http://debug.buildfire.com

then in the app (ship logs)
![image](https://cloud.githubusercontent.com/assets/492189/21371512/ac72b4de-c6c6-11e6-9b32-93d53c82fd9c.png)

Then select the [Launcher] Target. You can inspect your plugin similarly the same way you would on  a browser. From there is seems like the CSS is loading but the images within it are not.

I'll continue to dig in but would suggest using the debugger

**Comment by DanielHindi** [comment]
I think `<link href="assets/css/radioPlayer.css" rel="stylesheet">` is being loaded because when I delete the element you can see the plugin margins change. Thus, the problem must be from within the css file

**Comment by noahmiller** [comment]
The css file linted with no errors, but I eventually traced the problem to use of `.images` in url paths.  When I renamed the `.images` folder to `images` and changed css statements like this:

```css
background: url("../.images/crowd11.png") no-repeat center center fixed;
```

to this:

```css
background: url("../images/crowd11.png") no-repeat center center fixed;
```

the stylesheet loaded without error.

I haven't identified *why* use of `.images` in a url path should cause the entire stylesheet to fail only in BuildFire's Previewer app (again, it worked fine in BF's control panel and local testing), but things are working now, so I'll close this report.

However, since BuildFire recommends the use of a `.images` folder, I'd recommend adding a warning to your documentation regarding the above bug.

Also, regarding the suggestion to use http://debug.buildfire.com, note that it doesn't actually show the resources of a plugin (e.g. js and css files) or the styles on an element, so it proved quite unhelpful in this case.

<img width="198" alt="weinre resources" src="https://cloud.githubusercontent.com/assets/117264/21398119/337fac2c-c774-11e6-895b-e1cb3158d169.png">

<img width="677" alt="weinre styles" src="https://cloud.githubusercontent.com/assets/117264/21398123/36b4943e-c774-11e6-93aa-36afecf375aa.png">

**Comment by DanielHindi** [comment]
debug.buildfire.com uses weiner and isnt as strong as a Chrome Debugger. But it can get you out of a bind sometimes or at least expose some console logs on the device.

as for .images vs images this is recommended by Android so that images in these folders dont get exposed to the gallery. All our plugins use it. maybe it just wasn't encoded/escaped not quite sure. I will look further into this and add recommendations in the documentation.

Good to hear you are unblocked now
