### ISSUE TITLE
Background audio track info

### ISSUE THREAD

**Issue by noahmiller** [BuildFire/sdk#290]
My custom plugin is playing a [radio stream](http://sc6.shoutcaststreaming.us:8038/;stream/1) using `buildfire.services.media.audioPlayer`.  Playing the stream works fine, but in iOS the background audio control isn't showing any track info, like artist name.  That is, when I start the stream playing, lock the device, and pull up the control center audio controls, the title shows up as `http://sc6.shoutcaststream`, with no other information or image.

The audio stream is played more or less like so:

```javascript
var track = new Track('some title', stream_url, image_url, 'album name', 'artist name');
buildfire.services.media.audioPlayer.play(track);
```

How should extra track information be sent to BF's audioPlayer so that it populates the iOS currently playing data properly?

**Comment by mkuhnsbuildfire** [comment]
Hi, Noah. Sorry about the delay, we've been on vacation for the holidays. I'll take a look at this and let you know if I can help. 
You are able to play the songs, correct?

**Comment by noahmiller** [comment]
Yes, audio playback works fine.  The only issue is that the additional track data I'm providing via the `buildfire.services.media.audioPlayer` service is not populating the iOS control panel's audio player.

**Comment by rAbdelHadi** [comment]
We are not supporting that for the time being. Depending on how many developers ask for that functionality, we might look into this in the near future.
