### ISSUE TITLE
Receiving error "Upload unsuccessful. Missing image.png in resources folder." when trying to upload a plugin

### ISSUE THREAD

**Issue by tbergen1** [BuildFire/sdk#294]
I have cloned down the MediaRSSFeed Plugin and made some alterations to it.  When I attempted to upload it as a new customized plugin I get the error: "Upload unsuccessful. Missing image.png in resources folder."  This is a plugin that already exists in the Buildfire suite of plugins and I made no alterations to anything in the resources folder.  I only touched a few html and js files in the widget section of the plugin.

**Comment by rAbdelHadi** [comment]
does your zip file structure mimic this?

![pluginstructure](https://cloud.githubusercontent.com/assets/1897906/21507893/dcf70626-cc95-11e6-9b8f-7fcbc656a11b.png)

**Comment by tbergen1** [comment]
Yes, the problem seems to be with some extra layout images that are included in the resources folder.  The folder includes the icon.png and the image.png, but always errors out and gives the error I wrote above when those layout images are included in the folder.  These images were uploaded before though by the original creator, so I don't see why there would be errors with it now.

**Comment by mkuhnsbuildfire** [comment]
I looked at your files and they do appear to be right. I swapped out the resources folder from another one of our plugins (https://github.com/BuildFire/eventsManualPlugin) and it uploaded fine. Can you swap out our resources folder and then upload? Then swap out file by file from your resources folder and for each file you upload. See which file is corrupted.

**Comment by tbergen1** [comment]
Four of the layout images seem to be "corrupted," though there doesn't seem to be any indication that they actually are corrupted besides the fact that I cannot upload them while contained within the resources folder.  I can view them in other programs perfectly fine.  Any ideas why this would be?

**Comment by rAbdelHadi** [comment]
Can you give me access to your Github repository so we can download your plugin and check ?

**Comment by rAbdelHadi** [comment]
The issue has been fixed , Please try to upload your plugin again and let us know if you face any issues , Thank you .

**Comment by tbergen1** [comment]
Your fix worked.  I was able to upload the plugin files including all of the resource images without issue.  Thanks!
