### ISSUE TITLE
Remove gray 5px top border from custom plugin

### ISSUE THREAD

**Issue by noahmiller** [BuildFire/sdk#297]
Is it possible to remove the gray border from the top of a custom plugin?  It's about 5px tall, and appears to be attached to the iframe element or one of its parent elements.  In other words, it's not generated by any css from my custom plugin, nor does it appear to be customizable from my plugin's css.

The same top border is present on other plugins (e.g. the blog), but animates from gray to black as the plugin is loaded.  So if it's not possible to remove the border entirely, is it possible to change its color from gray to black?

Here's a screenshot demonstrating the border:
<img width="443" alt="custom plugin with gray top border" src="https://cloud.githubusercontent.com/assets/117264/21592927/de65dc78-d0df-11e6-96f5-60bc7c0578fa.png">

**Comment by abuturla** [comment]
@noahmiller I'm unable to reproduce this. Is there a specific custom plugin that I should take a look at? Also, where are you seeing this; is it when you're viewing a plugin via the previewer, directly in an app, in the plugin tester, etc? Thanks.

**Comment by abuturla** [comment]
@noahmiller I was able to track down your plugin and see the border that you are speaking of. From what I can tell the image crowd11.ping has a white border around the perimeter, and we are simply seeing the white top of that border. If we change the image then the border goes away.

**Comment by noahmiller** [comment]
Oh, yes, you're quite right.  I've fixed the image, and sorry for the bother of not figuring that out myself!
