### ISSUE TITLE
Using buildfire notifications

### ISSUE THREAD

**Issue by arc0489** [BuildFire/sdk#299]
Hi,
I was wondering if the buildfire.notifications.beep and buildfire.notifications.vibrate had been added to the notifications.js?
Ive got buildfire.notifications.confirm working, but there doesn't seem to be resources for the beep and vibrate

**Comment by abuturla** [comment]
@arc0489 It looks like there was an issue in the SDK that was preventing beep and vibrate from working properly. We'll start working on a fix and will keep you up to date with any changes.

**Comment by arc0489** [comment]
@abuturla I am also having trouble with buildfire.device.onAppBackgrounded is there a specific place this has to be added to the code? I have noticed examples with it being added to the app.js file. 

Is there a way to debug .onAppBackgrounded as well?

**Comment by abuturla** [comment]
@arc0489 If you don't mind, please open a new issue for this question, as it is an different topic. Thanks.

**Comment by abuturla** [comment]
@arc0489 We were able to resolve the issues with beep and vibrate. If this issue was for an existing app, the app will need to be resubmitted. Let me know if you have any questions. Thanks.

**Comment by arc0489** [comment]
@abuturla would you be able to submit our app for a hardbuild? 

As I am developing, I would love to be able to test using the vibrate and beep on my phone.

**Comment by abuturla** [comment]
@arc0489 I wouldn't submit the app myself, but I can help ensure that it is done. I'll need the name of your app for that.

You can test the beep and vibrate functionality using the BuildFire Previewer app. Simply load you app in the previewer and you can test all of its functionality, including custom plugins.

**Comment by arc0489** [comment]
@abuturla 
Liquori Fit is the app name.
Thanks

**Comment by abuturla** [comment]
@arc0489 You app has been resubmitted. It may take several days for they are approved.
