### ISSUE TITLE
Quote for Custom Dev

### ISSUE THREAD

**Issue by MichelleU** [BuildFire/sdk#300]
Hi, I have a client that would like the sliding images on the homescreen to fade in and out, instead of sliding. Can you please provide a quote for creating this? 
Thanks, Michelle

**Comment by abuturla** [comment]
Hello @MichelleU requests for custom development are typically handled by our Pro Services team. You can contact them directly at proservices@buildfire.com. Thanks.

**Comment by MichelleU** [comment]
Great! Thanks
