### ISSUE TITLE
Invalid Plugin.json Format

### ISSUE THREAD

**Issue by ahlamsalem** [BuildFire/sdk#303]
I'm having trouble uploading the plugin I created, I placed all the contents in a zip folder, but when I try to upload via the Plugin Manager - Upload Plugin button in the Buildfire developer site, I keep getting an error that the plugin.json is in an invalid format, even though it's valid json, and follows the example they have online [here](https://github.com/BuildFire/sdk/blob/master/plugins/myPlugin/plugin.json) 

I sent an email to their support, and they told me to post here. So, if anyone else has faced this issue I would appreciate the help.

Thanks!

**Comment by abuturla** [comment]
@ahlamsalem Can you show us the specific plugin.json file that you are having the issue with? Thanks.

**Comment by ahlamsalem** [comment]
Here it is, as you can see, it's pretty much like the example, so I don't understand why it's being rejected.

`{
  "author":"Ahlam Salem",
  "pluginName":"Schedule Appointment",
  "pluginDescription":"Plugin which allows users to schedule an appointment via Vetscene - Mobile",
  "supportEmail":"info@vetscene.com",
  "control":{
    "content":{
      "enabled":false
    },
    "design":{
      "enabled":false
    },
    "settings":{
      "enabled":true
    }
  },
  "features" : [],
  "languages": ["en"]
}`

**Comment by abuturla** [comment]
@ahlamsalem The JSON appears to be valid. What is the specific error message that you receive? 

I'm also wondering if there's something about your plugin that it doesn't like. What does the folder structure of your plugin look like?

**Comment by ahlamsalem** [comment]
This is the folder structure.

![plugin_folder_structure](https://cloud.githubusercontent.com/assets/24955600/21804951/5aeb55c4-d73a-11e6-9caf-1703e0ec9445.JPG)

The first time I created the zip, by right click the parent folder, when that didn't work, I even tried sending the contents to the zip thinking maybe it would work, but I got the same result.

This is the error message.

![upload_plugin_error_msg](https://cloud.githubusercontent.com/assets/24955600/21805078/e8079288-d73a-11e6-931a-e71b8b94ed8e.JPG)

Thanks!

**Comment by DanielHindi** [comment]
Hello Ahlam,
I took your plugin.json
````
{
    "author":"Ahlam Salem"
  , "pluginName":"Schedule Appointment"
  , "pluginDescription":"Plugin which allows users to schedule an appointment via Vetscene - Mobile"
  , "supportEmail":"info@vetscene.com"
  , "control":{
      "content":{ "enabled":false }
      , "design":{ "enabled":false }
      , "settings":{ "enabled":true }
  }
  , "features" : []
  , "languages": ["en"]
}
````
and pasted it as in into the [myPlugin] example into the SDK
Compressed it and uploaded and it was fine.


I would suggest trying several things:
1- make sure you only compress and upload plugin files. for example if you are using `git` you may have a `.git` folder thats invisible. Thats why you may notice the zip file is way too large
2- What are you using to compress/zip the folder? not all zip mechanisms are the same
3- try copying the [myPlugin] folder and move over your plugin into it one file at a time to see what causes it to fail


Hope this helps

**Comment by ahlamsalem** [comment]
@DanielHindi, @abuturla 

     Thanks for all the help. After a lot of trial and error, it turns out the plugin manager didn't like this snippet being excluded from the plugin.json. After adding it, I was able to upload my plugin. 

`,"widget":{

}`

   The problem now, is I have a bunch of plugins in my manager, is there any way to delete these?

**Comment by DanielHindi** [comment]
Ahlam good to know you are moving forward. But if you dont mind can you open up a separate ticket with the login issue so we can better address it. Also if you can include your app id located on the top right corner of the dev portal that would help greatly.

Thank you
