### ISSUE TITLE
Cannot upload plugin.  Receive error: "Upload unsuccessful. Incorrect zip file structure."

### ISSUE THREAD

**Issue by tbergen1** [BuildFire/sdk#304]
I made a change to a plugin for a client and I am unable to upload the zip file now.  I added two lines of code in an already existing file.  The structure of the plugin files was not changed.  I also zipped the plugin with the same program (7zip) that I have zipped every other iteration of the plugin with, all of which were able to be successfully uploaded.  Any ideas what could be causing this?

**Comment by abuturla** [comment]
@tbergen1 We'll take a look into it and will let you know what we find. Thanks.

**Comment by abuturla** [comment]
@tbergen1 it looks like a bug was recently introduced which was causing the issue. We have applied a fix, so it should no longer be an issue. Please try again and let us know if you still have the problem.

**Comment by tbergen1** [comment]
The issue was resolved by your fix.  Thanks!
