### ISSUE TITLE
Redirected to Login when trying to make changes in the Buildfire Dev Portal

### ISSUE THREAD

**Issue by ahlamsalem** [BuildFire/sdk#306]
Hi,
  I just uploaded my plugin to the Developer Portal and I would like to run some more tests. The problem I'm facing now, is that anytime I try to make a change in the Control Panel, I'm redirected to the Login page, and from there I'm caught in an endless loop. I tried using both Chrome and IE, same problem. 

 My Buildfire account/email is tied to another site [Vetscene-Apps](http://app.vetscene.com), I can work there just fine. The only issue I'm having is in the Developer Portal. My AppID is d702db2c-c74f-11e6-adc3-124a75f7ddd1.

  Any help is appreciated, thanks!

**Comment by DanielHindi** [comment]
are you trying to log into http://app.buildfire.com or http://app.vetscene.com/
you should be going to buildfire which has your test account d702db2c-c74f-11e6-adc3-124a75f7ddd1

**Comment by ahlamsalem** [comment]
Daniel,
    My login for both sites is the same. But the site I'm having trouble with is [http://app.buildfire.com](http://app.buildfire.com).

**Comment by DanielHindi** [comment]
i tried to login to your account through http://app.buildfire.com using your gmail username (i had to reset your password for a few minutes, its back to the original now) and i was able to log in just fine. Have you tried contacting the customer service department? they can reset your password if you need it or even grant you a separate login if it makes your life easier

**Comment by ahlamsalem** [comment]
Daniel,

     I don't have a problem logging in. I log in just fine, the problem is when I click "Control Panel", it opens in a new tab, and when I try to make any changes there, I get redirected to the login. I login, and run through the same steps, to only be redirected again to the login page.

**Comment by abuturla** [comment]
@ahlamsalem Does the error occur if you log in directly to the control panel using the following link? https://app.buildfire.com/pages/login.html

I think what would help if we had the exact steps to reproduce. Thanks.

**Comment by ahlamsalem** [comment]
@abuturla 
I just tried logging in directly from the link you provided, and the same thing happened. Thanks.

**Comment by abuturla** [comment]
@ahlamsalem  It turns out that your datastore write key was out of sync. We were able to correct this and it seems to have resolved your issue.

**Comment by ahlamsalem** [comment]
@abuturla 
Thank you! That solved the problem.

**Comment by abuturla** [comment]
@ahlamsalem Most likely the local plugin tester settings has the old/wrong "Datastore Write Key". You can update this value under the "Settings" section of your plugin tester.

I can email you the correct value. (You should keep the value private.)

**Comment by ahlamsalem** [comment]
@abuturla It seems like I may have corrupted one of the sdk files at some point, while trying to solve my previous issue. I got a fresh copy, and applied my key, it's fine now. Thanks again for the assistance!
