### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (appTheme.css Not Found)

### ISSUE THREAD

**Issue by sandeepchhapola** [BuildFire/sdk#31]
![uanble to load apptheme css](https://cloud.githubusercontent.com/assets/7790671/8925217/968c8608-3523-11e5-9474-5f5cac8e56b9.png)

**Comment by DanielHindi** [comment]
Issue fixed. Please pull latest SDK and try again

**Comment by sakshityagi** [comment]
So the previous error has been resolved. But now it gives another error in console "Cannot GET http://int2.myapp.buildfire.com/api/app/styles/appTheme.css?appId=c1f01898-341d-11e5-9d04-02f7ca55c361&liveMode=0 "
