### ISSUE TITLE
Possible on BuildFire platform?

### ISSUE THREAD

**Issue by krypt3d** [BuildFire/sdk#312]
I want to know if its possible to link multiple applications to be sent the same push notification on this platform. ie. Global Push Notification. I realize there is the RSS feed but it only sends daily/hourly. I am looking for something that could be instant.

Any info would be greatly appreciated. Thanks.

**Comment by abuturla** [comment]
@krypt3d Using out the of box functionality, it's only possible to configure a notification on a per app basis. 

Can you describe the scenario that you're thinking of in more detail, in order for us to see if there's possibly an alternative way of achieving it?

**Comment by krypt3d** [comment]
Hi there,

For example, there is an organization which has many subdivisions. Each of these subdivions would have their own mobile app. The directors of the organization would be able to send a push notification one time that goes to each application under their division. 

Need it instant instead of the RSS layout because of time sensitivity of info. Trying to get info if thre might be a way.

Hoping that makes sense. Thanks for your time.

**Comment by rcardiff1** [comment]
Hi krypt3d,

Robert here from BuildFire! If you'd like let's schedule a meeting to discuss in a bit more detail how we would approach your request. If you can send me an email to (rcardiff@buildfire.com) I will be happy to schedule a call.

Thank you,
Robert

**Comment by krypt3d** [comment]
Will do thanks.
