### ISSUE TITLE
audioPlayer service issues: "no home for this packet" and "buildfire.logger.log is not a function"

### ISSUE THREAD

**Issue by noahmiller** [BuildFire/sdk#313]
I'm having a couple issues with the audioPlayer service in a custom plugin.  These issues seem to have appeared in the last few weeks without any change to the plugin source code.  They're preventing control of the audio player.

1) A "no home for this packet (sad face) " warning in the `_acceptRequest` method of `postMaster.js`.  Here's what's in `e.data`:
```javascript
cmd: "mediaAPI.audioPlayer.play",
data: {
   album: undefined,
   artist: undefined,
   image: undefined,
   lastPosition: 0,
   startAt: 0,
   title: "Radio Ha-Ha!",
   url: "http://sc6.shoutcaststreaming.us:8038/;stream/1"
},
fid: "widget",
id: "2017-01-30T15:20:42.555Z0.8401004587975174",
instanceId: null
```

This failure occurs when calling `buildfire.services.media.audioPlayer.play(...)`.

2. "Uncaught TypeError: buildfire.logger.log is not a function"
    at Object.triggerOnEvent (audioPlayer.js:93)
    at _postMessageHandler (buildfire.js:175)

This exception occurs very frequently (many times a second).

The plugin is named "Radio Ha-Ha! Player".  The App ID is "20ccff06-c3b9-11e6-adc3-124a75f7ddd1".

**Comment by DanielHindi** [comment]
This may be a change in the SDK... Make sure you pull the latest and we will take a look into this warning asap

**Comment by noahmiller** [comment]
Thanks.  I downloaded and tested with the latest SDK (commit 7e5b9bbeed) just before submitting the issue.

**Comment by DanielHindi** [comment]
pull again and give it another go

**Comment by noahmiller** [comment]
That fixed both issues, thanks!

**Comment by noahmiller** [comment]
It looks like this fix hasn't been deployed to production -- or at least, the Previewer app is still showing symptoms of the bug.  Will you post back here when the fix is live?

**Comment by noahmiller** [comment]
The audio is also not continuing to play when the app is put in the background.  That was working before, so perhaps it's caused by the same bug, and fixed now.  I'll retest when this fix is deployed, and open a new issue if it's still not working.

**Comment by DanielHindi** [comment]
ITs scheduled to go out this morning. I'll keep you posted

**Comment by abuturla** [comment]
@noahmiller We've pushed out the fix. Let us know if the issues persists. Thanks.

**Comment by noahmiller** [comment]
It doesn't look like the fix was deployed.  When I reload the app in Previewer and debug using weinre, I still see this logged to console multiple times per second:

`
Error: TypeError: buildfire.logger.log is not a function. (In 'buildfire.logger.log(e)', 'buildfire.logger.log' is undefined)  Script: file:///var/mobile/Containers/Data/Application/DB7FA82E-0BB8-453F-B42F-4D5B0D61F382/Library/files/pluginTemplate/scripts/buildfire/services/media/audioPlayer.js  Line: 93  Column: 29  StackTrace: TypeError: buildfire.logger.log is not a function. (In 'buildfire.logger.log(e)', 'buildfire.logger.log' is undefined)
`

**Comment by DanielHindi** [comment]
We found a snag and had to revert the deployment. We are looking into it as we speak and will keep you posted

**Comment by abuturla** [comment]
@noahmiller Please try again now.

**Comment by noahmiller** [comment]
Yes, the audio player is working now, thanks.  Background audio is still not working, so I opened bug #315 for that.
