### ISSUE TITLE
Nav menu icon hard to click on Android

### ISSUE THREAD

**Issue by noahmiller** [BuildFire/sdk#314]
I haven't experienced this firsthand, but a client reported that trying to press the menu icon is a bit difficult on Android devices -- maybe the tap target is too small?  The issue was reported on a LG Flex2 (LGH955) Android phone.

**Comment by DanielHindi** [comment]
Thank Noah. We have been debating enlarging it and some other clickable areas in the app. Just running through some tests first before we move forward. We'll get back to you asap

**Comment by bkalaldeh** [comment]
We've increased the target size of the menu icon. Let us know if problem still persists.

**Comment by noahmiller** [comment]
Thanks!  I'll let the client know, and report back here only if he still has an issue with the click target.
