### ISSUE TITLE
Background audio no longer working

### ISSUE THREAD

**Issue by noahmiller** [BuildFire/sdk#315]
As of a few weeks ago, background audio appears to have stopped working on iOS for our plugin, when testing it using Previewer.  The plugin starts audio from a URL stream with `buildfire.services.media.audioPlayer.play(...)`, and includes the `BackgroundAudio` feature in the `plugin.json` file.  But when audio is playing and then the home button is clicked, the audio fades out and stops in a second or so.  The iOS background audio player control doesn't show the stream.

This was working in December, and we haven't changed anything relevant since then.

**Comment by DanielHindi** [comment]
The Previewer App may not have `BackgroundAudio` Enabled depending on who tests your app at Apple they may reject it since it not obviously necessary in the Previewer. I'll check with our build team on the latest build. That being said, this shouldnt affect your app.

**Comment by DanielHindi** [comment]
So our marketing team has a podcast they want to add the the Previewer App that will utilize background audio so Apple can consistently approve it. Getting a build out today. Update should be ready in 24-48 hours depending on Apple

**Comment by DanielHindi** [comment]
It should be live now. Can you confirm?

**Comment by noahmiller** [comment]
Thanks, yes, background audio is working in the new version of Previewer.
