### ISSUE TITLE
GeoFencing

### ISSUE THREAD

**Issue by bbrawley** [BuildFire/sdk#316]
Hi,

I'm using the buildfire platform and curious as to whether or not there is an existing plugin that would allow for geofencing? If so, can push notifications be set to interact with them? For instance, if a client enters within a certain proximity to a business location, it would trigger a push notification to the user. Is this functionality currently available? If not, would the platform support it?

Brandon

**Comment by rcardiff1** [comment]
Hi Brandon,

Robert here from BuildFire... Thank you for reaching out! We are actually in the process of developing this functionality and should be launching it in the next few months. 

The "Geo-fencing Push Notification" feature will do exactly what you outlined: "if a client enters within a certain proximity to a business location, it would trigger a push notification to the user.". 

If you want to reach out to me in 3-4 weeks I will give you an update! (Email: rcardiff@buildfire.com)

Thank you,
Robert

**Comment by bbrawley** [comment]
Thanks Robert! I'll check back in.
