### ISSUE TITLE
Get play status from audioPlayer

### ISSUE THREAD

**Issue by noahmiller** [BuildFire/sdk#317]
Is there a way to determine from `buildfire.services.media.audioPlayer` whether a track is currently being played?  When the app is in the background and a user plays or pauses audio with the device's background audio controls, my plugin obviously doesn't receive a `play` or `pause` event.  So when the app returns to the foreground, I'd like to be able to query the play status so I can update the play / pause button appropriately.

Listening for the `timeUpdate` event could work, except that that event arrives right after a `pause` event, so without some workaround like waiting for additional `timeUpdate` events I can't be certain it indicates audio is playing.

**Comment by DanielHindi** [comment]
We will expose the `isPaused(callback)` method. Should be out of QA by tomorrow. Simple callback interface ref: https://github.com/BuildFire/sdk/wiki/BuildFire-Audio-Player-Service

**Comment by DanielHindi** [comment]
Its live

**Comment by noahmiller** [comment]
Excellent, thanks for exposing that method.  That's solved the problem of missing play/pause events when the plugin isn't in the foreground.
