### ISSUE TITLE
UnwantHed Intercom on custom plugins

### ISSUE THREAD

**Issue by arc0489** [BuildFire/sdk#319]
I have created a couple custom plugins that have been published on our app for a while now. Just recently after setting up intercom during the WL process, intercom now shows up.
1. How do I get rid of this.
2. How can I use that intercom button to my advantage?

**Comment by DanielHindi** [comment]
Hello,
I believe this is a customer service question. I sent it over to them but to help identify your account I would contact support@buildfire.com

If this is a question about the SDK please feel free to reopen
