### ISSUE TITLE
Inquiry for real tracking app

### ISSUE THREAD

**Issue by Chrismavch** [BuildFire/sdk#321]
Hello! 

I am currently building my online shop using Shopify platform and would like to find out if I can use BuildFire platform to build an app and integrate it to my Shopify store afterwords.

My concern though is, because of the complexity of the features of the app I wish to create, might not be working with my Shopify template and platform I am using. 

I would like to create a live tracking mapping service for my customers! So when they place an order I, will be receiving that order and assign that order to a driver, then the client can check the actual order in realtime on a map! Something like uber rush app for example!

I would very much appreciate any help in this issue I'm facing!

Best regards!
Chris

**Comment by DanielHindi** [comment]
Hello Chris,

You can defiantly fork our open source plugin for shopify https://github.com/BuildFire/eCommercePlugin
to make it do anything you want. If you're need any help in doing so you are welcome to contact our Pro Services department proservices@buildfire.com they can better understand your needs and put you in contact with certified developers who can help you achieve this

**Comment by Chrismavch** [comment]
Thank you Daniel! Really appreciate your help! I'll send an email!
