### ISSUE TITLE
audioPlayer errors due to undefined settings

### ISSUE THREAD

**Issue by noahmiller** [BuildFire/sdk#322]
When calling `buildfire.services.media.audioPlayer.play(...)`, the errors listed below are logged.  I'm not sure if these exceptions are causing any bugs, though I'm finding that playing audio seems temperamental.  These errors are logged both in the local testing environment and in the online debugger (weinre).

These errors appear to be caused by `audioPlayer.settings` being `undefined`, which in turn appears to be caused by `window.localStorage.getItem('audioPlayer')` being `'{}'`.  This code (in `pluginAPI/mediaAPI.js`) that loads previously saved data sets `settings` to `undefined`:

```javascript
            /// get previously saved data
            var json = window.localStorage.getItem('audioPlayer');
            try {
                var rec = JSON.parse(json);
                t.settings = rec.settings;
```

Error messages:
```
postMessageHandler error: TypeError: Cannot read property 'volume' of undefined
    at Object.setSettings (mediaAPI.js:39)
    at PluginAPI.postMessageHandler (pluginAPI.js:227)
    at tryPMH (postMaster.js:44)
    at Object._acceptRequest (postMaster.js:55)
    at postMessageHandler (postMaster.js:29)

postMaster.js:47 postMessageHandler error: TypeError: Cannot read property 'autoJumpToLastPosition' of undefined
    at Object.play (mediaAPI.js:173)
    at PluginAPI.postMessageHandler (pluginAPI.js:227)
    at tryPMH (postMaster.js:44)
    at Object._acceptRequest (postMaster.js:55)
    at postMessageHandler (postMaster.js:29)
```

**Comment by DanielHindi** [comment]
Hello Noah,

We'll have a look into this and get back to you asap. If we find a bug we will fix it and keep you posted.

**Comment by abuturla** [comment]
@noahmiller We have a potential fix in place and are in the process of testing. it should be ready relatively soon.

**Comment by noahmiller** [comment]
It looks like this issue was fixed by a recent change to the `mediaAPI` code that guards use of `this.settings`.  Thanks for that fix!
