### ISSUE TITLE
Using proxy urls on buildfire

### ISSUE THREAD

**Issue by tbergen1** [BuildFire/sdk#331]
I am making modifications to the loyalty plugin that already exists to add some extra features.  I am essentially trying to access all user records who hold loyalty points to display in a management console.  The way the plugin does this is not straight forward to me, from what I am used to with working within the context of the Buildfire SDK.  The plugin implements some type of proxy URL ("https://loyalty.buildfire.com") and queries against specific endpoints on that ("https://loyalty.buildfire.com/addLoyaltyPoints", etc) to save and retrieve data.  Is this some feature that Buildfire offers outside of the Datastore?

**Comment by DanielHindi** [comment]
Correct. The loyalty plugin accesses its own legacy service built since the 1.0 version of buildfire. Since it's from the legacy system and really wasn't meant to be open to developers. It's apis are somewhat limited and not really documented.

**Comment by tbergen1** [comment]
Ok, that makes sense.  Thanks!
