### ISSUE TITLE
Issue in build fire developer portal

### ISSUE THREAD

**Issue by NileshSystematix** [BuildFire/sdk#333]
I have opened firefox browser in mac machine and opened build fire developer portal to generate new license for the plugin .

When I clicked on Generate New license key and filled all the fields and clicking on Generate button then popup is not closed and if user taps multiple times on generate button then multiple emails are going on the user's mail id. 

This case is similar with cancel button also.

Please check below attached url of video for it.

Video: https://www.screencast.com/t/PZAGkV9eRIiR

**Comment by DanielHindi** [comment]
Thank you for pointing this out. We will look into this asap.

**Comment by adyNabeelMadain** [comment]
@NileshSystematix, Thanks for reporting. This had been fixed.
