### ISSUE TITLE
POST datastore Unauthorised

### ISSUE THREAD

**Issue by pytechqudra** [BuildFire/sdk#339]
![untitled](https://cloud.githubusercontent.com/assets/26219400/23604682/bacf0bc8-027f-11e7-9d68-9054ad33684e.png)

Hello, Why i'm getting "datastore POST Error with URL" ?? how to resolve it??

**Comment by DanielHindi** [comment]
It seems like you're getting an unauthorized error. Which usually means you are trying to access the datastore with the wrong key. 

Can you explain a bit more on how you got here. Maybe share your app id so we can investigate it for you

**Comment by dhananjay1995** [comment]
Now i'm using publicData instead of Datastore.. its working fine. but can u explain the Difference between both?

**Comment by DanielHindi** [comment]
Datastore is a CMS database. Which means that:
* it is read and write on the control side
* Read only on the widget side
* needs to be published for apps to see the changes 
* supports offline mode

Publicdata is:
* read and write on both sides
* all changes are instant i.e. No draft and published modes
