### ISSUE TITLE
POST to datastore gives 403 Forbidden

### ISSUE THREAD

**Issue by tbergen1** [BuildFire/sdk#340]
I am currently making adjustments to the Loyalty Plugin that exists in the BuildFire ecosystem.  I have been switching out the code that interfaces with the older backend to code that works with the datastore.  Working with the datastore works perfectly fine when I am making requests in the control portion of the app, but every request I make in the widget portion gives me a 403 Forbidden error.  Here is a screen shot of what comes back when I try to insert a record into the datastore.  I have noticed that instanceID in the returned response is null.  I'm not sure if that has something to do with the issue, but I have no other way to tell since the error is pretty cryptic.

The App ID I am testing this under is 9fded20a-0668-11e6-a50f-124798dea82d.

![datastore error](https://cloud.githubusercontent.com/assets/8553822/23644636/3d721db2-02d6-11e7-8faa-8bb366eeffc9.png)

**Comment by DanielHindi** [comment]
Hello Tom,
I believe you missed a fundamental understanding of the DataStore

Datastore is a CMS database. Which means that:
* it is read and write on the control side
* Read only on the widget side
* needs to be published for apps to see the changes
* supports offline mode


However, something like Publicdata or userdata is:
* read and write on both sides
* all changes are instant i.e. No draft and published modes

**Comment by tbergen1** [comment]
Ah, yeah I completely forgot datsstore was readonly on the widget side.  I
will switch to using Publicdata.  Thanks.
