### ISSUE TITLE
Bulk Insert 200+ entries

### ISSUE THREAD

**Issue by arc0489** [BuildFire/sdk#343]
Hi,
I am having an issue with bulk insert. I am trying to import a csv with 200+ entries, however it seems like only 50 of the entries are being inserted. It saves one then skips 5, (1,7,12,17,22,27)

**Comment by abuturla** [comment]
@arc0489 Can show us the code that you are using, along with a sample dataset? Thanks.

**Comment by arc0489** [comment]
Sorry, I realized it was my fault, but also I realized I had to utilize the pages in datastore.search.
