### ISSUE TITLE
Can't upload new versions of plugin

### ISSUE THREAD

**Issue by tbergen1** [BuildFire/sdk#348]
I am having issues uploading a new version of the plugin that I am working on.  I have rezipped the new files and made sure that changes I made were reflected in those zipped files.  I am able to upload it .zip file without problem, but none of the changes I make are reflected in the plugins in the BuildFire dashboard.

**Comment by abuturla** [comment]
Can you tell us which app and plugin you are seeing this issue with?

**Comment by tbergen1** [comment]
The app I am testing it on is called ePub Reader - Test App and the plugin is called Loyalty Custom.

**Comment by abuturla** [comment]
@tbergen1 I uploaded a plugin with a test app, and it updated correctly.

Just to help clarify, are you using the "Upload Plugin" button or the "Update" button?

**Comment by tbergen1** [comment]
I am updating the existing plugin using the update button.  It asks
questions like is it backward compatible etc.

**Comment by abuturla** [comment]
@tbergen1 Thanks for the clarification. We will look into it.

**Comment by tbergen1** [comment]
This isn't an issue any longer.
