### ISSUE TITLE
SDK not loading plugin

### ISSUE THREAD

**Issue by arc0489** [BuildFire/sdk#349]
I am getting this error when trying to work in SKD

```javascript
Worker error error { target: Worker, isTrusted: true, message: "SecurityError: Failed to load worker script at "app//scripts/dist/mediaWorker.js"", filename: "", lineno: 0, colno: 0, currentTarget: Worker, eventPhase: 2, bubbles: false, cancelable: true, defaultPrevented: false }

SecurityError: Failed to load worker script at "app//scripts/dist/mediaWorker.js"

TypeError: Utility is undefined
```
I am just trying to load the plugin in the sdk

**Comment by abuturla** [comment]
@arc0489 Can you clarify what you mean by loading the plugin in the SDK? Are you referring to testing your plugin in the plugin tester?

**Comment by arc0489** [comment]
@abuturla trying to test the plugin using firefox

**Comment by arc0489** [comment]
@abuturla @DanielHindi 
I have tried to keep working on other plugins, but this error keeps popping up on every plugin that I have made so far. It kills any script I am trying to run. I can't work on anything at this point.

I need this resolved.  It looks like the mediaAPI is failing, and the audioPlayer is being called and fails, however I don't call it anywhere in my script.

**Comment by DanielHindi** [comment]
Can you explain a bit more on how this is blocking you? Even if it is logging to the console an error. It should block you
