### ISSUE TITLE
Image Lib, show dialog method not working.(Earlier it was working though)

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/sdk#35]
![screenshot from 2015-07-30 12 16 34](https://cloud.githubusercontent.com/assets/3328800/8977271/1ea1d3da-36b5-11e5-973d-689944fbf85a.png)

**Comment by DanielHindi** [comment]
Hello Sakshityagi, are you sure you have the completely updated SDK ?

**Comment by sakshityagi** [comment]
Hey Daniel, I just took latest pull of sdk and there were some changes. ImageLib is working now. Thanks.
