### ISSUE TITLE
Whenever I am storing styles in datastore then I am getting dataclone error.

### ISSUE THREAD

**Issue by MaggieMacwell** [BuildFire/sdk#355]
Hello Team,

Whenever I am storing 

uildfire.datastore.save({value: document.getElementById("button2").style},
         function(err,result){
         if(err)
         console.log("there was a problem saving your data");
        else
       console.log("your data has saved successfully");

         });
}

then I am getting "DataCloneError: The object could not be cloned." error so please help me in sorting this issue.

**Comment by DanielHindi** [comment]
Just to comment on this ticket for anyone else who may have this issue. When saving objects to any database. Your object must be serializable over transport layers.
