### ISSUE TITLE
using .pluginInstance

### ISSUE THREAD

**Issue by arc0489** [BuildFire/sdk#360]
Hi,
I am trying to use .pluginInstance.showDialog, however when I try to console.log the results after apply is hit. I keep getting null.
I am also trying to use the .get method, and I get undefined for the returned value.
The instance Id's are correct.

Am I doing something wrong?

`                $scope.find = function () {
                    buildfire.pluginInstance.showDialog({
                        skipPluginInstances: false,
                        hideAddPlugin:false
                    }, function (data) {
                        console.log(data);
                    });
                };
                $scope.getPlugin = function (x) {
                    console.log("Look Here YOOOOOOOOOOOOO");
                    console.log(x.data.deepLink);
                    buildfire.pluginInstance.get(x.data.deepLink.slice(19), function (instances) {
                        console.log(instances);
                    });

                };`

Am I doing something wrong?

**Comment by DanielHindi** [comment]
At first glance I'd say check your callbacks
The standard params are (error, results)
Where all your code is just function(results)

**Comment by arc0489** [comment]
Thanks, That is what it is. 
Can you do me a favor and update that on the gitHub how to use?
Thanks,

**Comment by DanielHindi** [comment]
Will do. Thank for pointing that out
