### ISSUE TITLE
Trying to upload getting invalid plugin.json

### ISSUE THREAD

**Issue by Hreacon** [BuildFire/sdk#364]
I've used a validator and combed through other areas of documentation and it appears I have a valid plugin.json but still getting the error. Company name replaced with me and app name replaced with just App. I've copied this from working uploadable projects. Whats going on?

{
  "author": "Me",
  "pluginName": "App",
  "pluginDescription": "App",
  "supportEmail": "support@me.com",
  "control": {
    "content": {
      "enabled": false
    },
    "design": {
      "enabled": false
    },
    "settings": {
      "enabled": false
    }
  },
  "widget": {
  },
  "features": [],
  "languages": [ "en" ]
}

**Comment by DanielHindi** [comment]
I copied your JSON object as-is into a dummy plugin and it worked just fine for me.

Can you give me a bit more information on the error you are getting? Are you sure its from plugin.json and not the folder structure? It could also be the compression you are using

**Comment by Hreacon** [comment]
![image](https://cloud.githubusercontent.com/assets/8097235/25246622/16e6526c-25bd-11e7-8a30-ff56033e1b2b.png)

I think the error message may not be very helpful. I'll try recreating the plugin.json file.

**Comment by Hreacon** [comment]
I tried adding the 'required' content, design, and settings folders in the control directory. Same error.

I have the required icon.png and image.png in the resources folder, I got errors for those when I first tried uploading (uploading beta product for testing)

**Comment by Hreacon** [comment]
I must have been copying some bad invisible character, when I copied it from the example plugin.json from https://github.com/BuildFire/sdk/wiki/How-to-submit-your-plugin it worked... strange.

**Comment by DanielHindi** [comment]
No problem. Happy to hear you're unblocked.
