### ISSUE TITLE
How to remove document from a given tag in datastore?

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#37]
I have inserted multiple document in a tag using 
```js
buildfire.datastore.insert({"firstName":"Laura","lastName":"Bascoe"},'names', function(){
    $scope.status='imported ' + data.length + ' names.';
    $scope.$apply();
});
```
How i can remove a document using datastore api. Is there any method available to remove data?

**Comment by DanielHindi** [comment]
You want to be careful with Delete. there is a `buildfire.datastore.delete` however there are two copies of a record, the live copy and the draft copy. Live is the copy that is produced after the plugin has been published. Just be sure when you delete that you delete only whats required. ie may be only the mode you're in and not the entire record. If you are in the CP you just wan to delete the draft

**Comment by deepakshrma** [comment]
buildfire.datastore.delete is not there in updated sdk.

**Comment by sandeepchhapola** [comment]
:+1: @deepakshrma buildfire.datastore.delete is not available.

**Comment by DanielHindi** [comment]
Please check again now

**Comment by deepakshrma** [comment]
Tried but its not working. Given sample snippet is not working. throws Error:
Cannot POST /plugin/delete/19475165/peoplePlugin/1/people/55bb71f9050434800913c60c

```js
Buildfire.datastore.delete(itemId, 'people', function (err, result) {
                        console.info(result)
                        if (err) {
                           return console.error('Error----------while removing people----', err)
                        }
                        ContentHome.items.splice(_index, 1);
                    });
```

![remove_api](https://cloud.githubusercontent.com/assets/7682731/9045829/134d1ade-3a44-11e5-81ad-1f9b72e05574.png)

**Comment by dahabi** [comment]
Please check it now

**Comment by deepakshrma** [comment]
:+1:  working fine
