### ISSUE TITLE
Gatweay Timeout on Plugin upload

### ISSUE THREAD

**Issue by jneumann** [BuildFire/sdk#370]
When I try to upload a new plugin to the dev portal the plugin looks like it is uploading, but after it reaches 100% it does not show up in the Plugin Manager. In the dev tools for my browser on Chrome and Firefox, I am getting a 504 REQUEST TIMEOUT error.

**Comment by abuturla** [comment]
@jneumann I was able to upload a plugin to the dev portal just now without any issues. Sometimes you might get a similar error when there's an issue with the plugin itself. For example, a plugin requires that certain folders are present. I would verify that your plugin has all of the necessary folders.

**Comment by DanielHindi** [comment]
Also might be file size? Do you know what size the zip file is? Sometimes we see uploads with `.git`folders zipped up in them. With multiple branches the `.git` folders can get pretty large

**Comment by jneumann** [comment]
I think it was the file size, thanks for your help. Is there any way there could be an error message displayed if this happens in the future?
