### ISSUE TITLE
Issue with zeroclipboard/ ng-clip, Copy to clipboard not working.

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#40]
We are using zeroclipboard/ ng-clip. It is not working with existing framework. I guess iframe sandbox attribute restrict it.

**Comment by DanielHindi** [comment]
Even with allow-same-origin?

**Comment by deepakshrma** [comment]
Yes. I guess there is some problem with iframe. Examples are working when it is without iframe

**Comment by DanielHindi** [comment]
in active. closing for now
