### ISSUE TITLE
buildfire.datastore.get syntex is inconsistent with other API

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#44]
https://github.com/BuildFire/sdk/wiki/How-to-use-Datastore#buildfiredatastoreget-tag-optional-id-optional-callback

Id is the second param, However is the first param in other API's

**Comment by dahabi** [comment]
we add new API getById , this API takes id and tag , and the old get API now only takes tag 

https://github.com/BuildFire/sdk/wiki/How-to-use-Datastore#buildfiredatastoregetbyid--id--tag-optional-callback

**Comment by deepakshrma** [comment]
fixed ;)
