### ISSUE TITLE
Can we get "id" of an item in response of "Buildfire.datastore.onUpdate()"?

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/sdk#46]
Let say I add a new item in my content section, then I need that item to be added in widget section also. So I use onUpdate method to get this data. What I receive in callback of onUpdate is : 
```
bodyContent: ""
data: Object
dateCrated: 1438584137784
deepLinkUrl: ""
fName: ""
iconImage: ""
lName: ""
position: ""
socailLinks: Array[0]
topImage: "https://imagelibserver.s3.amazonaws.com/c1f01898-341d-11e5-9d04-02f7ca55c361/b123dfd0-39aa-11e5-8c2c-712ea17a5363.png"
```
I need an "id" field also in this response.

**Comment by DanielHindi** [comment]
The notification is sent out asyc with the server call. however, I see what you mean. We will add it in for you.

**Comment by dahabi** [comment]
Fixed

**Comment by sakshityagi** [comment]
Its working now. Thanks.
