### ISSUE TITLE
Issue with datastore.search API

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#50]
The idea of $regex is not clear.
```js
searchOptions.filter = {"$or": [{"$json.fName":{"$regex":"/*"} }, {"$json.lName": {"$regex":"/*"}}]};
                    Buildfire.datastore.search(searchOptions, TAG_NAMES.PEOPLE, function (err, records) {
                        if (err)
                            console.error('There was a problem retrieving your data', err);
                        else {
                            ContentHome.items = records;
                            $scope.$digest();
                        }
                    });
```
this works and give me result
```js
[
  {
    "id": "55bfcca29e6745f0112866f4",
    "data": {
      "topImage": "",
      "iconImage": "",
      "fName": "Deepak Deepak",
      "lName": "Deepak Deepak",
      "position": "Deepak",
      "deepLinkUrl": "",
      "dateCreated": 1438633124929,
      "socailLinks": [
        
      ],
      "bodyContent": "Deepak"
    }
  },
  {
    "id": "55bfcf6b9e6745f0112866f5",
    "data": {
      "topImage": "",
      "iconImage": "",
      "fName": "zxzx",
      "lName": "asas",
      "position": "asas",
      "deepLinkUrl": "",
      "dateCreated": 1438633837250,
      "socailLinks": [
        
      ],
      "bodyContent": "sas"
    }
  }
]
```
But when i tried it like 
```js
searchOptions.filter = {"$or": [{"$json.fName":{"$regex":"/Dee"} }, {"$json.lName": {"$regex":"/Dee"}}]};  
// or [{"$json.fName":{"$regex":"/Dee/"} }, {"$json.lName": {"$regex":"/Dee/"}}]
                    Buildfire.datastore.search(searchOptions, TAG_NAMES.PEOPLE, function (err, records) {
                        if (err)
                            console.error('There was a problem retrieving your data', err);
                        else {
                            ContentHome.items = records;
                            $scope.$digest();
                        }
                    });
```
it gives me zero record
I also tried it with $text search. It is also not working
```js
searchOptions.filter = {"$json.fName":{"$text":value} };
                    Buildfire.datastore.search(searchOptions, TAG_NAMES.PEOPLE, function (err, records) {
                        if (err)
                            console.error('There was a problem retrieving your data', err);
                        else {
                            ContentHome.items = records;
                            $scope.$digest();
                        }
                    });
```
Error: Can't canonicalize query: BadValue unknown operator: $text

**Comment by dahabi** [comment]
you need to remove the slashes
`{"$or": [{"$json.fName":{"$regex":"Dee"} }, {"$json.lName": {"$regex":"Dee"}}]}`

and $text is not supported command

**Comment by deepakshrma** [comment]
Hello Dahabi,
It's working fine. However it does not fill my requirement. What it does it match exact name. For example: suppose i have three records
![search1](https://cloud.githubusercontent.com/assets/7682731/9096754/d0a2cc16-3bdc-11e5-8605-e75c5153add6.png)

And i search for "Da",It should return 2 record, Daniel and Daya. But it returns zero.

![search2](https://cloud.githubusercontent.com/assets/7682731/9096780/f9e2c1d0-3bdc-11e5-9efc-ba21f2a6450e.png)

When i Look for "Daya" then it returns exact same single record.

![search](https://cloud.githubusercontent.com/assets/7682731/9096801/1fdadd50-3bdd-11e5-99c5-bbe1758e00ff.png)

**Comment by DanielHindi** [comment]
Deepak Please see the example "exampleSImpleSearch" here https://github.com/BuildFire/sdk/blob/master/plugins/exampleSimpleSearch/widget/index.html#L28

It shows you a good wild card search on first name
![image](https://cloud.githubusercontent.com/assets/492189/9099230/f5113280-3b83-11e5-9d91-6ed273389673.png)

![image](https://cloud.githubusercontent.com/assets/492189/9099249/17c32d1a-3b84-11e5-968a-6c0d989fad90.png)

**Comment by deepakshrma** [comment]
Thanks!! working fine!
