### ISSUE TITLE
Response from onUpdate(), sometimes does not have field "tag"

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/sdk#51]
Steps:
1. Click on "Add new item". This opens a page.
2. Add image for item. This will trigger "onUpdate" method in widget section. I have logged the response and it looks like: ``{ checkDuplicate: false, id: "55c0ee3196eca9a411832ac1", obj: Object, tag: "people"}``
3. Then add first name. This will again trigger "onUpdate" method. But this time response will be like: 
``{ data: Object, id: "55c0ee3196eca9a411832ac1" }``(No `tag` field).
4. And so on if you add more fields like last name, position etc, response will not have`tag` field.

**Comment by dahabi** [comment]
we made some changes on datastore update API , now the updated object will return back with `onUpdate` and also the `tag`
please try it now

**Comment by sakshityagi** [comment]
Still didn't work for me.

**Comment by dahabi** [comment]
you don't need to use onUpdate in the content ,but please try it now

**Comment by sakshityagi** [comment]
The above steps that I have mentioned, I have written for widget section, not content. onUpdate() is called whenever there is some change in content section and I need to show same changes in widget section also.

**Comment by DanielHindi** [comment]
Sakshi, has your issue been resolved?

**Comment by sakshityagi** [comment]
Working now. Thanks.
