### ISSUE TITLE
What are the different options available for action and openIn in buildfire.actionItems API

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#55]
Like we have action: "linkToWeb", openIn: "browser"
what are the other option available ??
API
https://github.com/BuildFire/sdk/wiki/How-to-use-action-Items#buildfireactionitemsshowdialog-actionitem-optional--options-optional--callback

**Comment by DanielHindi** [comment]
There are many and we are adding to them. possibly even changing other but shouldnt affect your plugin

**Comment by deepakshrma** [comment]
Actually i am working on PeopleMigrator, for that i need it to convert old data to new.

**Comment by DanielHindi** [comment]
Please move this ticket to the other repo. * this portion should be handled by the patform
