### ISSUE TITLE
Issue with actionItem dialog

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/sdk#58]
![screenshot-localhost 63342 2015-08-06 11-43-53](https://cloud.githubusercontent.com/assets/3328800/9105009/a26103aa-3c30-11e5-8266-b6f88dc5ee69.png)

Action dropdown is not visible when dialog opens. After selection any action, then it shows complete dropdown.

**Comment by jdm135** [comment]
This should be fixed. Please give it another try.

**Comment by sakshityagi** [comment]
Working now. Thanks.
