### ISSUE TITLE
"How to create a Plugin" is not correctly linked in wiki home page

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#6]
Steps:
1. Go to https://github.com/BuildFire/sdk/wiki
2. Open *"How to create a Plugin"* page

Expected: link will open "How to create a Plugin" page
Actual: Refresh the same page

**Comment by ianblair44** [comment]
Here is the proper link. https://github.com/BuildFire/sdk/wiki/How-to-create-a-Plugin

Issue is resolved.
