### ISSUE TITLE
Is there any api available to create WYSIWYG?

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#64]
![wysiwyg](https://cloud.githubusercontent.com/assets/7682731/9178530/426dbbcc-3fb5-11e5-9cc0-378e0c7f1bb1.png)

**Comment by DanielHindi** [comment]
https://github.com/BuildFire/sdk/wiki/How-to-use-the-WYSIWYG-editor

**Comment by deepakshrma** [comment]
:100: :+1: Thanks Daniel
