### ISSUE TITLE
Issue with buildfire openWindow

### ISSUE THREAD

**Issue by abhaychauhan** [BuildFire/sdk#65]
Hi , 

Getting issue with "buildfire.openWindow(attrs.openLink,'_blank');". this code return error :

Uncaught TypeError: buildfire.openWindow is not a function.

Please replicate it. I am using updated sdk. 

![buildfireopenwindow](https://cloud.githubusercontent.com/assets/13364374/9180345/91d73508-3fbf-11e5-961f-c33d7df0264a.png)

**Comment by deepakshrma** [comment]
This is not part of sdk. Please check below mention api for performing this kind of task.
https://github.com/BuildFire/sdk/wiki/How-to-use-action-Items

**Comment by abhaychauhan** [comment]
This is not related to action. I am using this reference., and getting error.Where should i logged issue related to navigation? Please help me.

https://github.com/BuildFire/sdk/wiki/How-to-use-Navigation

**Comment by DanielHindi** [comment]
the namespace on the documentation was wrong. its:
`buildfire.navigation. ...etc`

**Comment by abhaychauhan** [comment]
Hi,

Now getting error " Uncaught TypeError: this._sendPacket is not a function" 
in "buildfire.navigation.openWindow(attrs.openLink,'_blank');"
please refer attached image.

Thanks
![buildfirenaviation](https://cloud.githubusercontent.com/assets/13364374/9191481/6825c8a4-401f-11e5-8844-9eded39b8f3a.png)

**Comment by DanielHindi** [comment]
please make you have latest SDK and try again

**Comment by mishraavi** [comment]
Thanks ,

Now it is working fine
