### ISSUE TITLE
Got unauthorized access after taking pull from sdk

### ISSUE THREAD

**Issue by sandeepchhapola** [BuildFire/sdk#66]
After getting pull from sdk buildfire.datastore.save returns error 
{ code: "error", message: "unauthorized access"}

![save error](https://cloud.githubusercontent.com/assets/7790671/9192029/ef9ec0ec-4024-11e5-846b-e43c10f8876e.png)

**Comment by sandeepchhapola** [comment]
Actually, this  occur when we add WYSIWYG editor using angular.

**Comment by NancyHaddad** [comment]
Bashar Kalaldeh: This is not related to WYSIWYG. it is a datastore security issue.
You need to have the correct "key" to be able to save to datastore

keys: {datastoreKey:"a1234-34f34-1awe234-23423"}

**Comment by deepakshrma** [comment]
@NancyHaddad : There should be unique standardize Error code like 401 Unauthorized, 400 Bad Request. It is hard to trace without error code.

**Comment by sakshityagi** [comment]
I am also getting unauthorized error for many api calls.

**Comment by DanielHindi** [comment]
Please check you app context

**Comment by DanielHindi** [comment]
If the datastore was setup to use key 123 then you try to access it with key 456 it will give you this error

**Comment by DanielHindi** [comment]
this may have been cause by the recent change on the appContext.js file please make sure you either hard code your proper context or create a brand new one

**Comment by DanielHindi** [comment]
`plugiTester/scripts/appContext.js`
