### ISSUE TITLE
Is there any media library available to watch, play audio song

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#70]
For our media content library, We need api where we can play video, audio from different source. There are multiple media source, Like vimeo, youtube, dailymotion. We need some consistent  api. Where we just have to pass url and type(audio and video).
![sasas](https://cloud.githubusercontent.com/assets/7682731/9222422/4deda114-410f-11e5-9c07-82fc06374f40.png)

**Comment by DanielHindi** [comment]
There are no api's for playing embedable video however there will be an api to play audio.  That is not released just yet

**Comment by deepakshrma** [comment]
awesome :+1:

**Comment by deepakshrma** [comment]
Leaving this ticket open to track API status ;)

**Comment by DanielHindi** [comment]
Audio support was released a white ago. Here is the documentation https://github.com/BuildFire/sdk/wiki/BuildFire-Audio-Player-Service
for others who may have the same question.
