### ISSUE TITLE
Can i build and check APK locally?

### ISSUE THREAD

**Issue by deepakshrma** [BuildFire/sdk#8]
As of now, I can create my app and test it on emulator available on buildfire. Is there any way to create or download update apk so that i can test it on real device locally.

**Comment by DanielHindi** [comment]
1. Once you are done developing your plugin, you upload it to your developer portal. 
2. It is then added automatically to your test application. 
3. You can add an instance of your plugin to your test app with test data. 
4. Your test app should be accessible with our hard emulator  on your test device.

**Comment by deepakshrma** [comment]
Nice. Thanks.
