### ISSUE TITLE
Need index and updated item both in editor.onItemChange() method for carousel implementation

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/sdk#81]
// this method will be called when you edit item details
        editor.onItemChange = function (item) {
            save(editor.items);
        };

Currently this method provide only updated item. We need index also for updating the item in array of carousel images.

**Comment by DanielHindi** [comment]
changes. made please pull and try again

**Comment by sakshityagi** [comment]
Working now. Thanks.
