### ISSUE TITLE
Buildfire.datastore.onUpdate() method returns obj inside obj.

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/sdk#92]
Earlier Buildfire.datastore.onUpdate() used to return an object in response like:

`{"tag" :"abc", "obj" : { }}`

Now it returns something like this:

`{"data" : { }, "tag" :"abc", "obj" : { "obj" : { }}}`

So, which one we should use to update the new result? `response.data` or  `response.obj.obj`

**Comment by dahabi** [comment]
you should use `response.data`  ,the old one `response.obj.obj` is deprecated and it will be removed soon

**Comment by dahabi** [comment]
you should use `response.data` ,the old one `response.obj.obj` is deprecated and it will be removed soon

**Comment by sakshityagi** [comment]
Ok. Thanks.
