### ISSUE TITLE
Need a way to unbind onRefresh method()

### ISSUE THREAD

**Issue by sakshityagi** [BuildFire/sdk#93]
Something like clear() method

**Comment by DanielHindi** [comment]
You can disable refresh
https://github.com/BuildFire/sdk/wiki/How-to-use-Datastore#buildfiredatastoredisablerefresh

does this work for you?

**Comment by sakshityagi** [comment]
Yupp. Disable refresh is working. Let me try using this. Will get back to you in case I still need help.
